### ISSUE TITLE
set markets from url (ex aggr.trade/btcusd)

### ISSUE THREAD

**Issue by Tucsky** [Tucsky/aggr#100]
proposal

aggr.trade/btcusd
v3.aggr.trade/btcusd+ethusd

should automatically create OR use existing workspace listening to given symbols

- Rules for matching (what exchanges and case of stablecoins quote currency names)
We could use user preferences to know which exchanges should be included in the matching, that would require to take that part of the settings out of the workspace to the main indexedDB database
Making search preferences  (ex: no distinction of stablecoin currency)  or exchanges preferences (ex: disabled exchange) common across all workspaces

- Base workspace to use
Use default workspace if no workspaceId is specified (aggr.trade/btcusd)
Allow user to set default workspace from the settings
Allow user to use workspace as a base aggr.trade/a1b2/btcusd+ethusd

**Comment by lmvdz** [comment]
Would love to have this, how can I help?

**Comment by lmvdz** [comment]
Another option could be to provide a url parameter `?workspace=<url to .json>` which will get auto loaded

**Comment by lmvdz** [comment]
![image](https://user-images.githubusercontent.com/2179775/175143034-03636363-daf1-4d72-9aa0-693a709fdd2a.png)

**Comment by lmvdz** [comment]
Okay it's working again, not sure what happened 👍

**Comment by Tucsky** [comment]
ahh what happened there ?? was this connectivity issue on your end or... the old site remained unchanged, weird that you don't have the chart loading there

> Hmm so how do I use it?
> https//v3.aggr.trade/btcusdt ?

Yes, [https://charts.aggr.trade/btcusd](https://charts.aggr.trade/btcusd), [https://charts.aggr.trade/btcusd,ethusd](https://charts.aggr.trade/btcusd,ethusd), [https://charts.aggr.trade/shibusd+dogeusd](https://charts.aggr.trade/shibusd+dogeusd)  etc

> For example, I need to be able to define the workspace for the user, which will consist of a chart + trades for 3 different tickers

Right now it just set on all panes on the workspace, choosing which pair goes where just from the url would be too messy, imo

Defining the workspace.json as a query parameter, assuming you were thinking of an url sounds impractical af, if you have the file, just drop it on. I like the idea of sharing a workspace tho, just like tradingview

**Comment by lmvdz** [comment]
This is my case:
![image](https://user-images.githubusercontent.com/2179775/175163431-aa2fd86d-c99c-4141-86d0-2180e1b53c0a.png)

When a person comes to my site I want to show them v3.aggr.trade, but as you can see I have 3 games running, so if I could append a workspace query parameter `https://v3.aggr.trade?workspace=<url.json>` which would load a layout like this:

![image](https://user-images.githubusercontent.com/2179775/175163882-9bf13b57-2df8-4e73-a227-a98b96b1393d.png)

If it's not practical that's okay, I am sure people will still be able to setup the aggr chart the way they want!

**Comment by lmvdz** [comment]
A possible unwanted side-effect would be having the url be `https://v3.aggr.trade/btcusdt` and I have custom chart setup which has a bunch of different pairs like this: 
![image](https://user-images.githubusercontent.com/2179775/175165291-716f8a6f-a860-439a-bce6-28cdb085b348.png)
It would completely ruin that workspace

**Comment by lmvdz** [comment]
> ahh what happened there ?? was this connectivity issue on your end or... the old site remained unchanged, weird that you don't have the chart loading there

No idea what happened there...

**Comment by lmvdz** [comment]
#227 Something like this is what I was thinking of

**Comment by StijnV007** [comment]
Is it also possible to set a timeframe using the url?
Like "https://charts.aggr.trade/ethusdt_1s" or "https://charts.aggr.trade/ethusdt_1tick"?

@lmvdz Tagging here, maybe you know this?

**Comment by lmvdz** [comment]
> Is it also possible to set a timeframe using the url? Like "https://charts.aggr.trade/ethusdt_1s" or "https://charts.aggr.trade/ethusdt_1tick"?
> 
> @lmvdz Tagging here, maybe you know this?

Not sure, don't think it's currently possible to do so in Tucsky's repo
