### ISSUE TITLE
Color-picker is not selecting the right color

### ISSUE THREAD

**Issue by OrangeChannel** [Tucsky/aggr#11]
The spectrum slider renders the full spectrum starting from the left and ending at the slider circle instead of ending at the right side.

![image](https://user-images.githubusercontent.com/10972040/121814486-566e3080-cc3f-11eb-9fd8-c02f9f14a2f9.png)
![image](https://user-images.githubusercontent.com/10972040/121814491-5c641180-cc3f-11eb-9f6b-d11ee17409b9.png)

**Comment by Tucsky** [comment]
![picker](https://user-images.githubusercontent.com/5738336/121821204-e6d85f80-cc97-11eb-9683-cca1af0b304e.gif)
Another issue with this picker is that is not selecting the color shown in the hollow circle (the one in the gradient box)

**Comment by Tucsky** [comment]
Fixed in 3.2.0
