### ISSUE TITLE
[Suggestion] Add BTCUSDt BITFINEX SPOT 

### ISSUE THREAD

**Issue by Fitzerald0x** [Tucsky/aggr#110]
Hey Tucsky, 

Loving Aggr, amazing job !

It seems BITFINEX:BTCUSDT is missing. There is a BTCUSDT for BITFINEX but it is the derivative market BITFINEX:BTCF0:USTF0.
Would love to have the data as BTCUSDT has a similar volume to BTCUSD. 

Merci pour ton travail !

Fitz

**Comment by Tucsky** [comment]
TIL 'ust' means 'USDT' on bitfinex !!
Merci :)

![image](https://user-images.githubusercontent.com/5738336/140614552-d1edf9fa-fe30-45cc-9e82-e4403b4c46ac.png)


No historical for this pair until today unfortunately, should have know better
