### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by BlindOSX** [Tucsky/aggr#113]
SSL certificate has expired, can't access anymore.

Thanks in advance.

**Comment by gimple** [comment]
Not sure what URL you are accessing showing an invalid/expired certificate, but it shows for me on v3.aggr.trade as being fine through until January 2022, from mid-October.

**Comment by BlindOSX** [comment]
yeah, the certificate was renewed about an hour after posting this so thanks for that, now it works perfectly. Closing the issue :)
