### ISSUE TITLE
Sounds got glitchy

### ISSUE THREAD

**Issue by n1s** [Tucsky/aggr#117]
hmm it worked ok and today the sound is very distorted. Tried on diff browsers - the same issue. Other apps sound OK. Any ideas why?

**Comment by Tucsky** [comment]
Sorry to hear that, nothing was changed on our side so I don't know

So does it feels laggy ?
By default sounds are generated on the fly
So when the browser is experiencing performance issue the sounds can get delayed a bit, or played a the same time which is sounds bad.

Using external sounds with playUrl(*url*) is generally faster

Would love to hear what it sounds like tho if you can record

**Comment by n1s** [comment]
It sounded more like broken HW but other apps were OK. Today it's ok but it's pretty low volatility so I'll update if this reoccurs.

Thank you Tucsky, pretty amazing tool that you created.
