### ISSUE TITLE
Trades agg should listen to XBTUSDT (not USD) since that is way more liquid currently

### ISSUE THREAD

**Issue by whyCPPgofast** [Tucsky/aggr#119]

**Comment by Tucsky** [comment]
heh I will enable it by default then
In the meantime you just have to add it
Both are monitored

**Comment by whyCPPgofast** [comment]
I had no idea you could add symbols with the search icon 🤦‍♂️

**Comment by whyCPPgofast** [comment]
You dont have to add it as default its fine. My bad.
