### ISSUE TITLE
[Suggestion] Hex color-picker

### ISSUE THREAD

**Issue by OrangeChannel** [Tucsky/aggr#12]
Would be nice to have the option to input a hex code, like `#3e63f4`, for the color picker since websites like cryptowat.ch save their themes with hex codes instead of RGBA 0-255.

**Comment by Tucsky** [comment]
![switch color format](https://user-images.githubusercontent.com/5738336/121821387-d8d70e80-cc98-11eb-866d-eb8ac00e6662.gif)
You can set in manual hex, the color will most likely be converted to proper rgb after

**Comment by Tucsky** [comment]
Closing this for now

**Comment by OrangeChannel** [comment]
Ah, didn't know that was clickable. That's awesome.
