### ISSUE TITLE
Liquidations Bybit 

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#124]
Hello, I can have access from other orderflow software liquidations on BTCUSDT // BTCUSD BYBIT but not on AGGR, why is it the case ? You can test and it has been a long time now, there is no liquidations showing up.

& It is the case for a lot of tickers (all of them?) from bybit.

Thanks for the great work your platform is incredible.

**Comment by Tucsky** [comment]
Thank you sir for the suggestion, support for Bybit liquidations has been added.
> & It is the case for a lot of tickers (all of them?) from bybit.

Perps only 😃  (most of bybit)

**Comment by airborse** [comment]
thank you for the speed !! have a great day sir
