### ISSUE TITLE
Is it possible to have a lagging indicator?

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#126]
I want to have the indicator 26 periods before the current candle

**Comment by lmvdz** [comment]
forgot about the 'offset' field!

**Comment by lmvdz** [comment]
Still having issues with creating the RSI, because I need the average of the up moves and average of the down moves...not sure how to do that with the scripting api

**Comment by Tucsky** [comment]
You do rsi like this

```
src = $price.close
change = src - src[1]
up = rma(Math.max(change, 0), options.length)
down = rma(-Math.min(change, 0), options.length)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
line(rsi)
```

**Comment by CedarX2** [comment]
> You do rsi like this
> 
> ```
> src = $price.close
> change = src - src[1]
> up = rma(Math.max(change, 0), options.length)
> down = rma(-Math.min(change, 0), options.length)
> rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
> line(rsi)
> ```

I am still having an issue. Can you please help. I copied the above script and pasted in the field it's saying Syntex error

**Comment by CedarX2** [comment]
> I want to have the indicator 26 periods before the current candle

I would like to add same to my chart. With RSI. Can you  please share your script with me?
I would like to upload it

**Comment by lmvdz** [comment]
The ichimoku already has an example of the offset

**Comment by CedarX2** [comment]
> The ichimoku already has an example of the offset 
> 
I mean how do I add RSI to my chat. What script should I used?
