### ISSUE TITLE
Never dared asking but: Aggreggated Volume profile ? How hard would it be to implement ? 

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#129]
Most of the traders I know at a high level that trade order flow are using volume profile to determine levels/ direction/ interest & more, It is a really important component of most traders, wondering if it is of any interest for you to implement it. 

Cheers incredible platform especially for free

**Comment by Tucsky** [comment]
Insanely hard 😄

**Comment by airborse** [comment]
fook!

**Comment by lmvdz** [comment]
Hmm, maybe overlaying a new ChartWidget and swapping the x/y ?
