### ISSUE TITLE
Adjust of liquidity 

### ISSUE THREAD

**Issue by linuxx5046** [Tucsky/aggr#13]
in the panel of STATS  when you want to change the name of the diferents items  TRADES , VOLUMEN etc the system dont work , its almost imposible to change the name  . i will try all , and in liquidations if you select lbuy , lsell , only the first one is show ,  not the two values in any temporality that you choose.

**Comment by Tucsky** [comment]
Thank you for the report good sir

**Comment by linuxx5046** [comment]
thanks to you to made a really nice software, im try to install it in localhost  too , with a serve of it ....i see all the "framework" but dont charge any data of the exchanges . i dont know what i did bad.  any idea ?  im a core linux user with knows of develop in a few languages, but never work in java. so im a litte bit lost.

**Comment by linuxx5046** [comment]
I made a json personalized file and import to the system ....and still dont charge the values.  what the hell i can be doing bad.   i use vivaldi browser. i will try to use other browser to see what happen.

**Comment by linuxx5046** [comment]
no....with firefox dont charge.....it appear that the others stats dont be avalaible and you cant do anything with them.

**Comment by Tucsky** [comment]
> if you select lbuy , lsell , only the first one is show , not the two values in any temporality that you choose.

Just create two buckets, one for buys liquidations and one for sells

**Comment by linuxx5046** [comment]
ok , i can create one two or a lot more of it.....but anyway i cant change the names . it put untitled bucket , and it remain like these in any way i try to change.

**Comment by Tucsky** [comment]
Have you checked recently ? Try reload page I believe I just fixed that

**Comment by linuxx5046** [comment]
true . now its working ! just update now !

**Comment by linuxx5046** [comment]
THANKS !

**Comment by Tucsky** [comment]
Glad to hear that!
Tbh in V2 the stats pane had a purpose, now the chart can do everything the stats pane do... And you have historical on some pairs... which stats cannot have atm
 I'm going to close this now if still issue with stats pane just let me know :)
