### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by MA-inv** [Tucsky/aggr#135]
Can devs do something ?

**Comment by MA-inv** [comment]
Looks like something is up with spot and perp cvds, once they are turned on it kills history

**Comment by Tucsky** [comment]
on it

**Comment by MA-inv** [comment]
now getting "too many requests"

**Comment by Tucsky** [comment]
should be good now just refresh / clear cache

**Comment by MA-inv** [comment]
thanks, still getting "too many requests: v" once i start to scroll back , i didn't change anything in my templates

**Comment by Tucsky** [comment]
@MA-inv 

There is a 30 requests per 15min window limit, the you have to wait... this has been the case for months
I added a 500 bars max per request to avoid huge queries of data that slow down everyone else and even crash the server like it was the case on friday.
So now you do more smaller requests to the server, as a result your may get that "error" faster than before

500 bars for 22 markets is 11.1k bars, and 22 markets is just an average

Sorry sir it is how it is 😓

**Comment by MA-inv** [comment]
No problem at all, your work is really appreciated, i wasn't aware and probably just went way over because of trying to get it to work in different browsers and refreshing etc .... now i know and will adapt :) thank you

**Comment by Tucsky** [comment]
No all indicators use the same data right now, independently of what they actually use . they won't query on their own
There is room for optimization on that for sure!! would require major refactoring tho
