### ISSUE TITLE
Big lags when opened for more then 10mins, but get instantly resolved when changing zoom from 1x to 0.9x

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#138]
Hi Tucksy, see title

Basically I have big lags when using refresh rate at less 500ms which is to be expected, but I think there could be some easy fixing to do around it since when I change the zoom of said chart panel, a cache, or whatever gets reset and I instantly don't have any lags anymore.

If u could please look into it. Thanks a lot sir

**Comment by Tucsky** [comment]
Yeah I noticed as well, so annoying 
Clearly a bug, looks like its in the lightweightcharts lib as well, I will investigate more but in the meantime please set high refresh rate, I set mine to 2s at least with many charts just to be safe

**Comment by airborse** [comment]
I see, all is good if you know then

**Comment by Tucsky** [comment]
There is a def a bug on the TV lightweight-chart lib
I'm gonna see if that's something they can fix or no https://github.com/tradingview/lightweight-charts/issues/946 

> but I think there could be some easy fixing to do around it since when I change the zoom of said chart panel

I'm going to do that temporarily
Every couple minute I call the chart full update (originally triggered by the change of zoom)
Fixed it on http://tucsky.github.io/aggr for now (test environment)

**Comment by airborse** [comment]
very cool- thanks for the follow up!

**Comment by airborse** [comment]
issue totally resolved for me. Thanks for the hard work as always man.
