### ISSUE TITLE
Liqs buggy

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#139]
![image](https://user-images.githubusercontent.com/95099018/146567472-6ab58e17-7e84-433a-ab70-97ad36fb40b0.png)

please look into liqs these are a little too big in my taste to not have an issue

**Comment by Tucsky** [comment]
interesting.. please export workspace so I can take a look

**Comment by airborse** [comment]
> interesting.. please export workspace so I can take a look ![image](https://user-images.githubusercontent.com/5738336/146569789-63f103d6-fbeb-4c6a-a1f2-317ff9e09cff.png)

![image](https://user-images.githubusercontent.com/95099018/146569985-0d0ce9eb-8c83-4293-abfb-aec06c839216.png)
 got fixed by itself when reloading.

**Comment by airborse** [comment]
sent u a pm with my workspace nonetheless.
