### ISSUE TITLE
small loop in indicator

### ISSUE THREAD

**Issue by kozy** [Tucsky/aggr#140]
For the calculation of an indicator i am trying to loop over a result and try to access a previous value of price. Trying this returns undefined for that value. Maybe this is done to prevent me from doing inefficient calculations but for this I need it. How would I approach this? 

```
src = $price.close
period = 50
var count = 0

for(; count < period; count++) {
  console.log(count) // 0..49
  console.log(src[10]) // normal result of price
  console.log(src[count])  // undefined
}

```

Thank you!

**Comment by Tucsky** [comment]
So there was a bug, it didn't like src[count] but that's fixed now.
However the script system need to know how many bars it has to keep for each variables, thats just a way to optimize it and avoiding keeping the past variable values for nothing.
So when you do src[10] (current bar - 10) it knows it has to keep **up to 11 values** in it
If you only do src[count] it doesn't know: in your example it will only keep 10 previous bars, while the for goes to 50

>How would I approach this?

What are you trying to achieve exactly ? Most of the time there is an alternative to using for in the script.
You have to think as the whole script IS the for loop

**Comment by kozy** [comment]
Oh thank you Tucsky, that was quick. Yes I trying to port an indicator from tv. In a calculation it loops over a few periods and uses that value so it is most efficient this way. At least to still keep it readable. Maybe I'll change it but it takes some time to get right anyway. But so far it works great now!
