### ISSUE TITLE
Unable to apply sources to multiple trade panels

### ISSUE THREAD

**Issue by dmitry86** [Tucsky/aggr#141]
I set up 3 panels (via the duplicate button), for three different exchanges. When I tick the sources they are being applied to all three panels, instead of being applied individually per panel. E.G. I cannot have a separate panel per exchange.

![image](https://user-images.githubusercontent.com/9531076/146777509-8f7723ab-5d2b-47ca-823e-d5de1376e4d0.png)

Thanks

**Comment by Tucsky** [comment]
thankfully I cannot reproduce the issue 😃 

https://user-images.githubusercontent.com/5738336/146781414-4c60047b-0f5b-41b2-bd36-e4ca442ae12f.mov

Eventually send me your workspace (settings->blue button->download) by pm so I can test
If it doesn't matter try start fresh by reseting everything (settings->reset)

**Comment by dmitry86** [comment]
Thanks for looking into it, for some reason I am not able to do the same. Any change I made to the source or coin, it gets replicated across all the panels.
I'll send you my workspace now.

**Comment by LIn-Lin-Git** [comment]
Hey Dev, i would like to know if you can add " open interest" too?  it would great, thank a lot

**Comment by Tucsky** [comment]
Open interest would b great 👍🏼

**Comment by LIn-Lin-Git** [comment]
Do you know when « open interest » will be available ? Can’t wait

**Comment by Tucsky** [comment]
I've no plan to add oi. However PR s are always encouraged! 😃
