### ISSUE TITLE
1H Liquidations ∆ 

### ISSUE THREAD

**Issue by iipx7070** [Tucsky/aggr#143]
Hello programmer 
1H Liquidations ∆ Is Disabled
shows the value NAN 
Please fix it

**Comment by Tucsky** [comment]
Sry sir there was a typo.
Fixed now

**Comment by sbeslic** [comment]
The value of **NaN** is fixed but right now it only shows **0** even though there are liquidations

![1h liquidations delta](https://user-images.githubusercontent.com/11785250/148071449-2ad9bff4-bf2c-4f1b-9343-e0c12da329a6.png)
