### ISSUE TITLE
Some changes / upgrades / questions

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#144]
Hello, loving the platform as always, here are some things I think would benefit from it as well as some questions I have. 

IMO having a midline on the counter pane, so we can assess more effectively where there is an imbalance when comparing multiple counters would be cool. Also changing colors of it would be cool.
-Only having it display the total volume / trades would be welcomed too
 
Is the aggregating at 1000ms for example is working as attended (more than likely I'm misunderstanding here), like if there is aggr of each second for every trade in that time, there should be at max 1 trade a second right? It's not the case.

Is there some way to put the ohlc on a histogram? I'm trying to have a basic volatility indicator so I can assess absorption more easily and have a historic of it, just having the total range of each candlestick and then comparing it to volume/ delta would be enough for me, but I've been in the doc for some time and tested a lot & can't make it work. Is it possible?

Also, only recently, the chart pane doesn't save whatever i try to do.

Thanks a lot sir

**Comment by Tucsky** [comment]
The 1s aggregation means that once a trade come for a certain market and side, it will keep adding into this trade for up to 1s **as long as there isn't a trade of the opposite side being reported** for the same market. So seeing more than 1 every sec is very normal.

I thin the counter and stats pane aren't very useful, I find them very much useless tbh so not my priority to update for now. Appreciate the suggestions tho
Chart do a better job at showing the same information

> just having the total range of each candlestick

That's sounds simple enough for the built in scripting 😀
Maybe I am missing something but I think
 `histogram($price.high-$price.low)` or `histogram(Math.max($price.open,$price.close)-Math.min($price.open,$price.close))` should do

> Also, only recently, the chart pane doesn't save whatever i try to do. 

Ugh 😩 
Are you talking about updates on the indicators or the chart options itself ?
Let me know if you see anything sus in the console (F12 -> console tab) for me it just works so I really don't know sry

Thank you again for feedbacks!

**Comment by airborse** [comment]
I see for the counter panel, yes I mostly agree, I just used it to see if there was any anomaly or offside exchanges on volatile moves, but no issue really as it is really gadget and not really reliable yes.

Thanks a lot for the indie, I'll try that!

I found a way, to save it you need to duplicate the chart panel & only then does it work!

thanks a lot for the work as always, have a good one.

**Comment by airborse** [comment]
Also understood for the explanation of aggr, makes a lot of sense now.

**Comment by airborse** [comment]
Also now, trying to overwrite or touch anything really about indicators makes the whole thing crash

**Comment by Tucsky** [comment]
> Also now, trying to overwrite or touch anything really about indicators makes the whole thing crash

I Ve seen this happen , usually from non closed paranthesis or things like that.. will try to put a limit to prevent triggering an infinite loop when I get back next yr 👍
