### ISSUE TITLE
Referencing price source not working

### ISSUE THREAD

**Issue by sbeslic** [Tucsky/aggr#151]
Referencing price source not working properly since latest update from December.
For example:
`candlestick(BITFINEX:BTCUSD.open, BITFINEX:BTCUSD.high, BITFINEX:BTCUSD.low, BITFINEX:BTCUSD.close)`
is throwing ` Syntax error: Unexpected identifier`.

It happens on every market/price source. The problem is with _**.low**_ method, since changing it from .low to any other (.open, .high, .close) removes the error and lets pane plot the price (but without .low wicks, of course). 

Providing screenshots below, in the first one you can see the thrown error and missing candlestick below the popup window and on the 2nd you can see changing .low to .close which prompts price to show beneath the popup (albeit without .low wicks)

![Error using candlestick  low](https://user-images.githubusercontent.com/11785250/148070754-7b3eec69-bcc2-4eee-9c23-8aa04c0f6712.png)

![close instead  low working fine](https://user-images.githubusercontent.com/11785250/148070757-2d8a4c10-0bae-435e-b4e7-b36e82ef3ab0.png)

**Comment by Tucsky** [comment]
temporary fix for this

`candlestick(BITFINEX:BTCUSD.open,BITFINEX:BTCUSD.high,BITFINEX:BTCUSD['low'],BITFINEX:BTCUSD.close)`

**Comment by sbeslic** [comment]
thank you very much :)

**Comment by Tucsky** [comment]
Alright closing now as it is fixed :)
