### ISSUE TITLE
issue with accessing historical vbuy/vsell values

### ISSUE THREAD

**Issue by annulus** [Tucsky/aggr#155]
Hi Tucsky!

I'm trying to access historical vol (vbuy/vsell) values, but I'm unable to do so:
- referencing via array id is not working, e.g. vbuy[2] => undefined
- could use sum, but it only works if the length is static, not a variable (not suitable to use within a loop)
working
`sum(vbuy, 4) - sum(vbuy, 3)`
not working
`n = 4; sum(vbuy, n) - sum(vbuy, n - 1)`

Is this intentional?

Thanks,
David

**Comment by Tucsky** [comment]
> referencing via array id is not working, e.g. vbuy[2] => undefined

but you can copy it's value into a variable that can then be accessed like an array
arr_vbuy=vbuy
histogram(arr_vbuy[5])

**Comment by annulus** [comment]
works like a charm, thanks for the quick help!
