### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by airborse** [Tucsky/aggr#159]
Whatever I do I get this, help 
![image](https://user-images.githubusercontent.com/95099018/149675879-19278bc7-0b33-4a90-9bcc-932c827699ce.png)

was working yesterday and for no reason today it doesn't

thanks a lot sir

**Comment by Tucsky** [comment]
server got tempo banned for certain exchanges maybe it will fix itself

**Comment by airborse** [comment]
i see thanks

**Comment by annulus** [comment]
unfortunately it's still not working.

wouldn't it be better to discard the problematic exchanges (mark these under the Markets) and use/render data on the available ones?
having incomplete data is better than having nothing.

**Comment by Tucsky** [comment]
@annulus you were stuck in loading too ? did you lose any data ?

**Comment by airborse** [comment]
still not working; can provide template if needed

**Comment by Tucsky** [comment]
@airborse And now ? 
Yes template might help

**Comment by airborse** [comment]
still the same

sent email, thanks a lot sir

**Comment by Tucsky** [comment]
@airborse check mail

**Comment by airborse** [comment]
@Tucsky answered
