### ISSUE TITLE
[Suggestion] Option to increase font size

### ISSUE THREAD

**Issue by aza0092** [Tucsky/aggr#16]
Currently, only way to increase font size is via increasing the entire browser zoom level. The current font size is incredibly small especially for large monitor sizes.

**Comment by Tucsky** [comment]
Closing this for now as the overall font size has been increased + ability to zoom in or out on each panes 
![image](https://user-images.githubusercontent.com/5738336/123993934-2eb3f200-d9cd-11eb-9272-ee6a75b83488.png)
