### ISSUE TITLE
FTX SPOT CVD - what I'm doing wrong?

### ISSUE THREAD

**Issue by n1s** [Tucsky/aggr#164]
Trying to plot SPOT CVD for FTX. It gives 0 line but seems correct?
`plotline(cum((FTX:BTC/USD.vbuy) - (FTX:BTC/USD.vsell)))`

**Comment by Tucsky** [comment]
@n1s  Hi
You need to add FTX:BTC/USD to the chart (search -> FTX:BTC/USD -> add)

**Comment by n1s** [comment]
That was it. I thought I was running a default template and FTX is included lol. Sorry for hassle, your help as usually invaluable - thank you!
