### ISSUE TITLE
v3 - chart's markets popup clipping & tab title

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#17]
Hi Tuscky,

![image](https://user-images.githubusercontent.com/2179775/121964109-a4169600-cd30-11eb-90b1-5fb60bf778f2.png)

As you can see in the image above:

- the popup is clipping the markets on the right side of the pane
- the title of the tab is incorrect, I chose all ETHUSD from the search pane, but the tab title still shows the data for BTC

**Comment by Tucsky** [comment]
![btceth](https://user-images.githubusercontent.com/5738336/122282211-70cc3680-ceeb-11eb-9279-5bdd6ea8610c.gif)

**Comment by Tucsky** [comment]
Closing this now
