### ISSUE TITLE
Hide/Add Trickers for Price Pane

### ISSUE THREAD

**Issue by uBadRequest** [Tucsky/aggr#18]
I was interested in also tracking large orders made in other fiat currencies, like GBY or JPY but I see they are included in the price ticker. 

I think it would be cool if we could remove or add other tickers to the price ticker.

**Comment by Tucsky** [comment]
I believe that's already the case ? 
In the "prices" pane, click the 🔍 icon to attach / detach markets to it.

Not sure If I'm getting what you were asking tbh
