### ISSUE TITLE
chart breaks for unknown reason

### ISSUE THREAD

**Issue by lechef1** [Tucsky/aggr#186]
different cvds hide under each other instead of being structured https://prnt.sc/VbgEgvK8B7Y-
orders on all previous versions were much much smoother, now laggy af, especially when on low order amount like $1000 its literally freezing 
chart breaks for unknown reason https://prnt.sc/8KIZV2ihzeOU , observer on 5m+ timeframes

ps i use the tool through a browser, any suggested fixes of those problems are welcomed + if there's a chance for auto-updates to be disabled that would help too

**Comment by Tucsky** [comment]
@lechef1 pls upload workspace here so I we can see what's wrong with your template

**Comment by lechef1** [comment]
> @lechef1 pls upload workspace here so I we can see what's wrong with your template

.json file type not supported
