### ISSUE TITLE
problem with implementing historical data

### ISSUE THREAD

**Issue by DarwynBruelemans** [Tucsky/aggr#19]
Okay first of all I would like to say thanks for the work here.
I'm having a problem with the implementing of the historical data. 
I'm running the aggr-server in docker on port 3000 just like the guide.
the local app also works and shows the realtime graph but i can't get it to show historical data.
any idea what i'm missing? my .env.development looks like this:
API_URL=http://localhost:3000/historical/2021-06-14-21/2021-06-14-22/1h/COINBASE:BTC-USD

Am i formatting wrong or?

**Comment by Tucsky** [comment]
You should use timestamp (ms) for start & end and timeframe **in ms**  as well


for 10s chart `http://localhost:3000/historical/1623713570000/1623719538999/10000`

**Comment by Tucsky** [comment]
I'm assuming that was the issue, Imma close this one now. Don't hesitate to reopen if any more question
