### ISSUE TITLE
"Bitget Exchanges"

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#191]
Hello sir Tucsky i have Qestion ). Maybe add Exchanges Bitget. This stock exchange is growing very fast and is already 2# Rank Volumen?

![image](https://user-images.githubusercontent.com/100996537/156887955-9519ea76-ee63-489d-9ef3-3ee36e8f909f.png)

**Comment by Tucsky** [comment]
Never heard of it

**Comment by Knf69** [comment]
> Never heard of it

This exchange is growing very fast, it already has a larger volume than ftx.
See how quickly the volume goes up there today 17% +

**Comment by maestrolol** [comment]
Please could u add this exchange?? It is very important!!

**Comment by Knf69** [comment]
> Never heard of it

hi are you working to add this exchange?

**Comment by Knf69** [comment]
> @Knf69 I think this is pretty self explanatory : <img alt="image" width="743" src="https://user-images.githubusercontent.com/5738336/158210912-ecd45bf4-c79f-4e1e-9e56-53dc9429a6f1.png"> ERV is Estimated Real Volume Like I said, I don't know anyone that trade on it, and putting the reported vs real volume into perspective it just looks like a very very shady exchange if you ask me

How about 2 of these perp exchanges? 
[https://gyazo.com/6e6de27b5097311dfd0724b6dc2409bb](url)

**Comment by Knf69** [comment]
> @Knf69 I think this is pretty self explanatory : <img alt="image" width="743" src="https://user-images.githubusercontent.com/5738336/158210912-ecd45bf4-c79f-4e1e-9e56-53dc9429a6f1.png"> ERV is Estimated Real Volume Like I said, I don't know anyone that trade on it, and putting the reported vs real volume into perspective it just looks like a very very shady exchange if you ask me


Look at the volume on this Bitget 

https://cdn.discordapp.com/attachments/878292477503737889/955446097990549554/7085da336054355f08c4a0a6aaf23f86.png

**Comment by adeacetis** [comment]
It's been added recently
