### ISSUE TITLE
deribit not found bug

### ISSUE THREAD

**Issue by nemanja3** [Tucsky/aggr#196]
no pairs are found when searching for deribit exchange : 

![image](https://user-images.githubusercontent.com/26413661/158676667-dbf54e60-2837-4132-aed0-ba8cde078fcc.png)

![image](https://user-images.githubusercontent.com/26413661/158676473-6a7a053a-6618-4ade-bc40-f2ef4d5c9239.png)

**Comment by Tucsky** [comment]
Thanks for the report sir
Deribit updated their api and discontinued the old one. Amazing!
hard refresh now should download the new deribit products infos
