### ISSUE TITLE
Browser "brave"

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#198]
Hello, for over 2 weeks there has been a problem with showing transactions .Not showing most Spot / Perp exchanges. Now I see that it shows normally on another browser and there is still the same problem on Brave.

**Comment by Tucsky** [comment]
No issue whatsoever with showing trades on brave browser
![2022-03-20 12 50 25](https://user-images.githubusercontent.com/5738336/159160879-389408c7-7841-403c-b33d-6afac467642d.gif)

Can you verify that the trades are not filtered in any way (threshold, type, market or exchange) ?

**Comment by Knf69** [comment]
I will check and let you know  :)

**Comment by Knf69** [comment]
OK all good now work. Close topic
