### ISSUE TITLE
Audio issue 

### ISSUE THREAD

**Issue by armyanov** [Tucsky/aggr#199]
Hi!

I'm having an issue where there is a sound played for the insignificant orders,those that are even below the 10% of significant threshold, even though the "include orders down to 10% of significant orders" checkmark is not enabled.

But when I enable the checkmark, then the sound is played only for significant trades and those above 10% of their value.

Is there a way to disable the sound for all insignificant orders? To have only for the ones that are above the threshold2, like in the legacy version? Or can I adjust the 10% threshold to something that I like? If so, where should I look?

**Comment by Tucsky** [comment]
what checkmark are you referring to ?
![image](https://user-images.githubusercontent.com/5738336/159163640-bf68136e-66c5-4386-ac6c-2c986df23f69.png)

**Comment by adeacetis** [comment]
This app version is deprecated. I am closing this issue since it's been added to the newer version.
