### ISSUE TITLE
Stock exchanges perp 

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#200]
what would you say to Adding these very popular perp + spot exchanges? 
Kucoin is a huge stock exchange and has a real Gateio volume, which is also well known to me. 

![Kucoin Gate](https://user-images.githubusercontent.com/100996537/159265258-44021276-8e0b-490e-83c5-80aa9ddd246f.png)

**Comment by nemanja3** [comment]
kucoin would be very nice to havea agree

**Comment by maestrolol** [comment]
Yes please, having these would be very useful!

**Comment by adeacetis** [comment]
Kucoin has been added

GateIO is in testing
