### ISSUE TITLE
Kraken Futures perp pairs are labeled as spot

### ISSUE THREAD

**Issue by lechef1** [Tucsky/aggr#204]
![image](https://user-images.githubusercontent.com/100498720/163780052-71c179ab-8597-4633-a8de-aeff59e1278c.png)

thats some bs low vol futures contract, not spot

**Comment by adeacetis** [comment]
Thank you for reporting this.

This is fixed in Today's version available on aggr.trade.

![image](https://github.com/Tucsky/aggr/assets/20586054/bff08f71-6d40-49de-8d2b-7d56ad8c86da)
