### ISSUE TITLE
Cannot read properties of undefined (reading 'year')

### ISSUE THREAD

**Issue by dairefagan** [Tucsky/aggr#205]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- I refreshed and adding the indicator again and there was nothing in the console.
- Database export attached

![image](https://user-images.githubusercontent.com/12515718/164070248-40d85b2b-f7bb-4965-aad2-5c413ad0871c.png)

### Describe the issue

Indicator started reporting error today without code change. Seems to be caused by the candlestick function.

```
src(50) = $price.close

var cvd = cum(BINANCE:btcusdt.vbuy-BINANCE:btcusdt.vsell)

candlestick(ohlc(cvd), title = SPOT)
[hn82_bug-report.txt](https://github.com/Tucsky/aggr/files/8515584/hn82_bug-report.txt)

```
### Steps to reproduce

Use the candlestick function.

(Preferably from a clean environment / incognito mode)
1. Import the aggr database or paste the code into a script

**Comment by Tucsky** [comment]
Ayy thanks for posting this proper bug report with db export and everything, very much appreciated 🙏🏼 
However this gonna be very easy here all you have to do is to put `time` as second param of the ohlc function

```
src(50) = $price.close

var cvd = cum(BINANCE:btcusdt.vbuy-BINANCE:btcusdt.vsell)

candlestick(ohlc(cvd, time), title = SPOT)
```

I did changed something in the way script function work under the hood yesterday, but idk, to me that time parameter has always been there. if that wasn't the case let me know

**Comment by dairefagan** [comment]
Thanks, that worked great and thank you for sharing aggr. I have been using it for a few weeks without time, the error just started this morning.

Could you please explain the difference between cbuy and vbuy as to me these read like they both describe the same thing. I would have assumed the number of reported buys at market is the same as the number or market orders executed?

> vbuy amount of buys (reported amount of buys at market) 
> cbuy number of market orders executed on buy side

Is there some way I could display a fixed price scale but with dynamic values across it (rather than just the current bar) either vertically or horizontally, and have you any plans to introduce tickers for any derivatives data like open interest or funding rates?

**Comment by Tucsky** [comment]
vbuy is the volume of buy (amount in quote currency) while cbuy is the number of individual market buys (number of reported market trade that is a buy)

Ive no plan in implementing any of that, sorry
