### ISSUE TITLE
showing no more data

### ISSUE THREAD

**Issue by Glazehtc** [Tucsky/aggr#206]
when i open up aggr in my pc ( i tried multiple browsers and assured its not the problem  with the browser) its showing like this 
Here is a link to the screenshot of how it looks like:
https://drive.google.com/file/d/1DHF7UHhtcbKHZZBlHvT8AXQkElWMIZGj/view?usp=sharing

i cant get the historical data when i open up it on my pc.
can anybody help with that please?

**Comment by Tucsky** [comment]
Send me an export of your template so I can take a look

**Comment by Glazehtc** [comment]
{
  "version": 5,
  "createdAt": 1650690603074,
  "updatedAt": 1650690624020,
  "name": "Untitled",
  "id": "pkf3",
  "states": {
    "panes": {
      "_id": "panes",
      "locked": false,
      "panes": {
        "chart": {
          "id": "chart",
          "name": "",
          "type": "chart",
          "markets": [
            "BINANCE_FUTURES:btcusd_perp",
            "BITFINEX:BTCUSD",
            "BITMEX:XBTUSD",
            "BYBIT:BTCUSD",
            "COINBASE:BTC-USD",
            "DERIBIT:BTC-PERPETUAL",
            "FTX:BTC-PERP",
            "FTX:BTC/USD",
            "BINANCE:btcusdt",
            "BINANCE_FUTURES:btcusdt",
            "BITFINEX:BTCUST",
            "BITFINEX:BTCF0:USTF0",
            "BITMEX:XBTUSDT",
            "BYBIT:BTCUSDT",
            "COINBASE:BTC-USDT",
            "FTX:BTC/USDT"
          ]
        },
        "trades": {
          "id": "trades",
          "name": "",
          "type": "trades",
          "markets": [
            "BINANCE_FUTURES:btcusd_perp",
            "BITFINEX:BTCUSD",
            "BITMEX:XBTUSD",
            "BYBIT:BTCUSD",
            "COINBASE:BTC-USD",
            "DERIBIT:BTC-PERPETUAL",
            "FTX:BTC-PERP",
            "FTX:BTC/USD",
            "BINANCE:btcusdt",
            "BINANCE_FUTURES:btcusdt",
            "BITFINEX:BTCUST",
            "BITFINEX:BTCF0:USTF0",
            "BITMEX:XBTUSDT",
            "BYBIT:BTCUSDT",
            "COINBASE:BTC-USDT",
            "FTX:BTC/USDT"
          ],
          "settings": {
            "tradeType": "trades",
            "thresholds": [
              {
                "amount": 100000
              }
            ],
            "liquidations": {
              "amount": 50000
            }
          }
        },
        "liquidations": {
          "id": "liquidations",
          "name": "REKTS",
          "type": "trades",
          "markets": [
            "BITFINEX:BTCUSD",
            "BITMEX:XBTUSD",
            "BITMEX:XBTUSDT",
            "BITFINEX:BTCF0:USTF0",
            "BINANCE_FUTURES:btcusdt",
            "BINANCE_FUTURES:btcusd_perp",
            "DERIBIT:BTC-PERPETUAL",
            "FTX:BTC-PERP",
            "FTX:BTC/USD",
            "FTX:BTC/USDT",
            "BYBIT:BTCUSD",
            "BYBIT:BTCUSDT"
          ],
          "settings": {
            "tradeType": "liquidations"
          }
        }
      },
      "layout": [
        {
          "i": "chart",
          "type": "chart",
          "x": 0,
          "y": 0,
          "w": 20,
          "h": 24,
          "moved": false
        },
        {
          "i": "trades",
          "type": "trades",
          "x": 20,
          "y": 0,
          "w": 4,
          "h": 20,
          "moved": false
        },
        {
          "i": "liquidations",
          "type": "trades",
          "x": 20,
          "y": 20,
          "w": 4,
          "h": 4,
          "moved": false
        }
      ]
    },
    "settings": {
      "_id": "settings",
      "preferQuoteCurrencySize": true,
      "aggregationLength": 1,
      "disableAnimations": false,
      "calculateSlippage": null,
      "autoHideHeaders": true,
      "theme": "dark",
      "backgroundColor": "rgb(23,27,41)",
      "textColor": "",
      "timezoneOffset": 0,
      "useAudio": false,
      "audioVolume": 1,
      "audioFilters": {
        "PingPongDelay": true,
        "Compressor": false,
        "Delay": false,
        "HighPassFilter": true,
        "LowPassFilter": false
      },
      "settings": [
        "other",
        "chart",
        "stats",
        "counters",
        "audio",
        "workspaces"
      ],
      "searchTypes": {
        "historical": true,
        "spots": true,
        "perpetuals": true,
        "futures": false,
        "normalize": true,
        "mergeUsdt": true
      },
      "searchQuotes": {
        "USD": true,
        "USDT": true,
        "UST": true
      },
      "favoriteTimeframes": {},
      "normalizeWatermarks": true,
      "alerts": true,
      "alertsColor": "red",
      "alertsLineStyle": 2,
      "alertsLineWidth": 2,
      "alertsClick": false
    },
    "exchanges": {
      "BINANCE": {
        "disabled": false,
        "fetched": true
      },
      "BINANCE_FUTURES": {
        "disabled": false,
        "fetched": true
      },
      "BINANCE_US": {
        "disabled": true,
        "fetched": false
      },
      "BITFINEX": {
        "disabled": false,
        "fetched": true
      },
      "BITMEX": {
        "disabled": false,
        "fetched": true
      },
      "BITSTAMP": {
        "disabled": true,
        "fetched": false
      },
      "BYBIT": {
        "disabled": false,
        "fetched": true
      },
      "COINBASE": {
        "disabled": false,
        "fetched": true
      },
      "DERIBIT": {
        "disabled": false,
        "fetched": true
      },
      "DYDX": {
        "disabled": false,
        "fetched": false
      },
      "FTX": {
        "disabled": false,
        "fetched": true
      },
      "HITBTC": {
        "disabled": true,
        "fetched": false
      },
      "HUOBI": {
        "disabled": true,
        "fetched": false
      },
      "KRAKEN": {
        "disabled": true,
        "fetched": false
      },
      "OKEX": {
        "disabled": true,
        "fetched": false
      },
      "PHEMEX": {
        "disabled": true,
        "fetched": false
      },
      "POLONIEX": {
        "disabled": true,
        "fetched": false
      },
      "_id": "exchanges"
    },
    "chart": {
      "indicatorsErrors": {},
      "indicators": {
        "cvd": {
          "enabled": true,
          "name": "CVD",
          "description": "Cumulative Volume Delta",
          "script": "plotline(cum(vbuy - vsell))",
          "options": {
            "priceScaleId": "cvd",
            "priceFormat": {
              "type": "volume"
            },
            "color": "#3BCA6D",
            "scaleMargins": {
              "top": 0.84,
              "bottom": 0
            }
          },
          "id": "cvd",
          "createdAt": 1650690603054,
          "updatedAt": null,
          "series": [
            "cvd"
          ]
        },
        "liquidations": {
          "enabled": true,
          "name": "Liquidations",
          "description": "Liquidations by side",
          "script": "plothistogram(lbuy, color=options.upColor)\nplothistogram(-lsell, color=options.downColor)",
          "options": {
            "priceFormat": {
              "type": "volume"
            },
            "priceScaleId": "volume_liquidations",
            "upColor": "rgb(255,76,243)",
            "downColor": "rgb(255,183,77)",
            "scaleMargins": {
              "top": 0.75,
              "bottom": 0.17
            }
          },
          "id": "liquidations",
          "createdAt": 1650690603054,
          "updatedAt": null,
          "series": [
            "liquidations",
            "1xnfysux"
          ]
        },
        "price": {
          "enabled": true,
          "name": "Price",
          "script": "plotcandlestick(avg_ohlc(bar))",
          "options": {
            "priceScaleId": "right",
            "priceFormat": {
              "auto": true,
              "precision": 1
            },
            "priceLineVisible": true,
            "lastValueVisible": true,
            "borderVisible": true,
            "upColor": "rgba(100, 157, 102, 0)",
            "downColor": "rgb(156,52,62)",
            "borderUpColor": "rgb(59, 202, 109)",
            "borderDownColor": "rgb(239,67,82)",
            "wickUpColor": "rgb(59, 202, 109)",
            "wickDownColor": "rgb(239,67,82)"
          },
          "id": "price",
          "createdAt": 1650690603054,
          "updatedAt": null,
          "series": [
            "price"
          ]
        },
        "volume": {
          "enabled": true,
          "name": "Volume",
          "description": "Volume + delta",
          "script": "if (upColor === 0) {\n  if (options.showDelta) {\n    upColor = options.upBgColor\n    downColor = options.downBgColor\n  } else {\n    upColor = options.upColor\n    downColor = options.downColor\n  }\n}\n\nif (options.showDelta) {\n  plothistogram({ time: time, value: Math.abs(vbuy-vsell), color: vbuy - vsell > 0 ? options.upColor : options.downColor})\n}\n\nplothistogram({ time: time, value: vbuy + vsell, color: vbuy > vsell ? upColor : downColor })",
          "options": {
            "priceFormat": {
              "type": "volume"
            },
            "upColor": "rgb(59,202,109)",
            "downColor": "rgb(235,30,47)",
            "priceScaleId": "volume",
            "scaleMargins": {
              "top": 0.84,
              "bottom": 0
            },
            "showDelta": true,
            "upBgColor": "rgba(59,202,109,0.5)",
            "downBgColor": "rgba(235,30,47,0.5)"
          },
          "id": "volume",
          "createdAt": 1650690603054,
          "updatedAt": null,
          "series": [
            "volume",
            "32x28gcv"
          ]
        }
      },
      "priceScales": {
        "right": {
          "scaleMargins": {
            "top": 0.04,
            "bottom": 0.26
          }
        },
        "cvd": {
          "scaleMargins": {
            "top": 0.84,
            "bottom": 0
          }
        },
        "volume_liquidations": {
          "scaleMargins": {
            "top": 0.75,
            "bottom": 0.17
          }
        },
        "volume": {
          "scaleMargins": {
            "top": 0.84,
            "bottom": 0
          }
        }
      },
      "layouting": false,
      "timeframe": 10,
      "refreshRate": 1000,
      "showLegend": true,
      "fillGapsWithEmpty": true,
      "forceNormalizePrice": false,
      "showHorizontalGridlines": false,
      "horizontalGridlinesColor": "rgba(255,255,255,.1)",
      "showVerticalGridlines": false,
      "verticalGridlinesColor": "rgba(255,255,255,.1)",
      "showWatermark": true,
      "watermarkColor": "rgba(255,255,255,.1)",
      "hiddenMarkets": {},
      "barSpacing": null,
      "_id": "chart"
    },
    "trades": {
      "liquidations": [
        {
          "id": "liquidation_threshold",
          "amount": 50000,
          "buyColor": "rgba(236,64,122,0.5)",
          "sellColor": "rgba(255,152,0,0.5)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*2,0,,,'sine')\nplay(329.63, srqtR, srqtR*4,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*2,0,,,'sine')\nplay(440, srqtR, srqtR*4,0.08,,,'sine')"
        },
        {
          "id": "liquidation_significant",
          "amount": 100000,
          "buyColor": "rgba(236,64,122,0.6)",
          "sellColor": "rgba(255,152,0,0.7)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*4,0,,,'sine')\nplay(329.63, srqtR, srqtR*6,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*4,0,,,'sine')\nplay(440, srqtR, srqtR*6,0.08,,,'sine')"
        },
        {
          "id": "liquidation_huge",
          "amount": 200000,
          "buyGif": "flying money",
          "sellGif": "flying money",
          "buyColor": "rgba(236,64,122,0.7)",
          "sellColor": "rgba(255,152,0,0.8)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*4,0,,,'sine')\nplay(329.63, srqtR, srqtR*8,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*4,0,,,'sine')\nplay(440, srqtR, srqtR*8,0.08,,,'sine')"
        },
        {
          "id": "liquidation_rare",
          "amount": 1000000,
          "buyGif": "explosion",
          "sellGif": "explosion",
          "buyColor": "rgb(156,39,176)",
          "sellColor": "rgb(255,235,59)",
          "buyAudio": "var srqtR = Math.min(1, gain / 10)\nplay(329.63, srqtR, 1,0,,,'sine')\nplay(329.63, srqtR, srqtR*10,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 10)\nplay(440, srqtR, 1,0,,,'sine')\nplay(440, srqtR, srqtR*10,0.08,,,'sine')"
        }
      ],
      "thresholds": [
        {
          "id": "threshold",
          "amount": 100000,
          "buyColor": "rgba(119, 148, 92, 0.25)",
          "sellColor": "rgba(239, 67, 82, 0.25)",
          "buyAudio": "play(659.26, gain / 10, 0.1 + gain / 7)",
          "sellAudio": "play(493.88, gain * 1.5 / 10, 0.1 + gain / 7)"
        },
        {
          "id": "significant",
          "amount": 250000,
          "buyColor": "rgb(100, 157, 102)",
          "sellColor": "rgb(239, 67, 82)",
          "buyAudio": "play(659.26, 0.05 + gain / 10, 0.2 + ratio * 0.23,0,,0);\nplay(830.6, 0.05 + gain / 10, 0.2 + ratio * 0.23, 0.08,,0)",
          "sellAudio": "play(493.88, 0.05 + gain * 1.5 / 10, 0.2 + ratio * 0.23,0,,0);\nplay(392, 0.05 + gain * 1.5 / 10, 0.2 + ratio * 0.23, 0.08,,0)"
        },
        {
          "id": "huge",
          "amount": 1000000,
          "buyGif": "cash bullish",
          "sellGif": "cash bearish",
          "buyColor": "rgb(59, 202, 109)",
          "sellColor": "rgb(235, 30, 47)",
          "buyAudio": "play(659.26, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0,,0);\nplay(830.6, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0.08,,0);\nplay(987.76, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0.16,,0);\nplay(1318.52, 0.05 + gain / 10, 0.1 + ratio * 0.23, 0.24,,0)",
          "sellAudio": "play(493.88, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0,,0);\nplay(369.99, 0.05 + gain * 1.5 / 10, 0.2, 0.08,,0);\nplay(293.66, 0.05 + gain * 1.5 / 10, 0.2, 0.16,,0);\nplay(246.94, 0.05 + gain * 1.5 / 10, 0.1 + ratio * 0.23, 0.24,,0)"
        },
        {
          "id": "rare",
          "amount": 10000000,
          "buyGif": "explosion",
          "sellGif": "explosion",
          "buyColor": "rgb(0, 255, 127)",
          "sellColor": "rgb(217, 31, 28)",
          "buyAudio": "play(659.26, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0,,0);\nplay(830.6, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0.08,,0);\nplay(987.76, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0.16,,0);\nplay(1318.52, 0.05 + gain / 10, 0.1 + ratio * 0.13, 0.24,,0)",
          "sellAudio": "play(493.88, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0,,0);\nplay(369.99, 0.05 + gain * 1.5 / 10, 0.2, 0.08,,0);\nplay(293.66, 0.05 + gain * 1.5 / 10, 0.2, 0.16,,0);\nplay(246.94, 0.05 + gain * 1.5 / 10, 0.1 + ratio * 0.13, 0.24,,0)"
        }
      ],
      "audioThreshold": null,
      "multipliers": {},
      "showThresholdsAsTable": true,
      "maxRows": 100,
      "muted": false,
      "audioPitch": null,
      "audioVolume": null,
      "showTradesPairs": false,
      "tradeType": "trades",
      "showLogos": true,
      "monochromeLogos": false,
      "thresholdsMultipler": 1,
      "_id": "trades"
    },
    "liquidations": {
      "liquidations": [
        {
          "id": "liquidation_threshold",
          "amount": 50000,
          "buyColor": "rgba(236,64,122,0.5)",
          "sellColor": "rgba(255,152,0,0.5)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*2,0,,,'sine')\nplay(329.63, srqtR, srqtR*4,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*2,0,,,'sine')\nplay(440, srqtR, srqtR*4,0.08,,,'sine')"
        },
        {
          "id": "liquidation_significant",
          "amount": 100000,
          "buyColor": "rgba(236,64,122,0.6)",
          "sellColor": "rgba(255,152,0,0.7)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*4,0,,,'sine')\nplay(329.63, srqtR, srqtR*6,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*4,0,,,'sine')\nplay(440, srqtR, srqtR*6,0.08,,,'sine')"
        },
        {
          "id": "liquidation_huge",
          "amount": 200000,
          "buyGif": "flying money",
          "sellGif": "flying money",
          "buyColor": "rgba(236,64,122,0.7)",
          "sellColor": "rgba(255,152,0,0.8)",
          "buyAudio": "var srqtR = Math.min(1, gain / 4)\nplay(329.63, srqtR, srqtR*4,0,,,'sine')\nplay(329.63, srqtR, srqtR*8,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 6)\nplay(440, srqtR, srqtR*4,0,,,'sine')\nplay(440, srqtR, srqtR*8,0.08,,,'sine')"
        },
        {
          "id": "liquidation_rare",
          "amount": 1000000,
          "buyGif": "explosion",
          "sellGif": "explosion",
          "buyColor": "rgb(156,39,176)",
          "sellColor": "rgb(255,235,59)",
          "buyAudio": "var srqtR = Math.min(1, gain / 10)\nplay(329.63, srqtR, 1,0,,,'sine')\nplay(329.63, srqtR, srqtR*10,0.08,,,'sine')",
          "sellAudio": "var srqtR = Math.min(1, gain / 10)\nplay(440, srqtR, 1,0,,,'sine')\nplay(440, srqtR, srqtR*10,0.08,,,'sine')"
        }
      ],
      "thresholds": [
        {
          "id": "threshold",
          "amount": 100000,
          "buyColor": "rgba(119, 148, 92, 0.25)",
          "sellColor": "rgba(239, 67, 82, 0.25)",
          "buyAudio": "play(659.26, gain / 10, 0.1 + gain / 7)",
          "sellAudio": "play(493.88, gain * 1.5 / 10, 0.1 + gain / 7)"
        },
        {
          "id": "significant",
          "amount": 250000,
          "buyColor": "rgb(100, 157, 102)",
          "sellColor": "rgb(239, 67, 82)",
          "buyAudio": "play(659.26, 0.05 + gain / 10, 0.2 + ratio * 0.23,0,,0);\nplay(830.6, 0.05 + gain / 10, 0.2 + ratio * 0.23, 0.08,,0)",
          "sellAudio": "play(493.88, 0.05 + gain * 1.5 / 10, 0.2 + ratio * 0.23,0,,0);\nplay(392, 0.05 + gain * 1.5 / 10, 0.2 + ratio * 0.23, 0.08,,0)"
        },
        {
          "id": "huge",
          "amount": 1000000,
          "buyGif": "cash bullish",
          "sellGif": "cash bearish",
          "buyColor": "rgb(59, 202, 109)",
          "sellColor": "rgb(235, 30, 47)",
          "buyAudio": "play(659.26, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0,,0);\nplay(830.6, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0.08,,0);\nplay(987.76, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0.16,,0);\nplay(1318.52, 0.05 + gain / 10, 0.1 + ratio * 0.23, 0.24,,0)",
          "sellAudio": "play(493.88, 0.05 + gain / 25, 0.1 + ratio * 0.23, 0,,0);\nplay(369.99, 0.05 + gain * 1.5 / 10, 0.2, 0.08,,0);\nplay(293.66, 0.05 + gain * 1.5 / 10, 0.2, 0.16,,0);\nplay(246.94, 0.05 + gain * 1.5 / 10, 0.1 + ratio * 0.23, 0.24,,0)"
        },
        {
          "id": "rare",
          "amount": 10000000,
          "buyGif": "explosion",
          "sellGif": "explosion",
          "buyColor": "rgb(0, 255, 127)",
          "sellColor": "rgb(217, 31, 28)",
          "buyAudio": "play(659.26, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0,,0);\nplay(830.6, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0.08,,0);\nplay(987.76, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0.16,,0);\nplay(1318.52, 0.05 + gain / 10, 0.1 + ratio * 0.13, 0.24,,0)",
          "sellAudio": "play(493.88, 0.05 + gain / 25, 0.1 + ratio * 0.13, 0,,0);\nplay(369.99, 0.05 + gain * 1.5 / 10, 0.2, 0.08,,0);\nplay(293.66, 0.05 + gain * 1.5 / 10, 0.2, 0.16,,0);\nplay(246.94, 0.05 + gain * 1.5 / 10, 0.1 + ratio * 0.13, 0.24,,0)"
        }
      ],
      "audioThreshold": null,
      "multipliers": {},
      "showThresholdsAsTable": true,
      "maxRows": 100,
      "muted": false,
      "audioPitch": null,
      "audioVolume": null,
      "showTradesPairs": false,
      "tradeType": "liquidations",
      "showLogos": true,
      "monochromeLogos": false,
      "thresholdsMultipler": 1,
      "_id": "liquidations"
    }
  }
}

**Comment by Glazehtc** [comment]
here is the Link to the template that iam using, iam using the default template, nothing additional.
https://drive.google.com/file/d/1TStKEDv-utcvCBm7_OkC0xAsmElfyKNW/view?usp=sharing

**Comment by Tucsky** [comment]
Please check that you got accurate time https://time.gov/
A system clock time drifting by 100+ seconds could be the cause..
![image](https://user-images.githubusercontent.com/5738336/164791317-db1a241c-c6b2-4945-87cf-973273829753.png)

Also if you know how to open chrome dev tool, network tab
The first historical request made have those timestamp in the url
The first number in it must be < than the date in the response header

![image](https://user-images.githubusercontent.com/5738336/164792261-b757a6aa-7f72-48ff-858d-c33f01d4960e.png)

can't think of anything else rn sry
