### ISSUE TITLE
v3.1.0 25 Apr Search function no longer working

### ISSUE THREAD

**Issue by sfroach** [Tucsky/aggr#208]
### Describe the issue
Rebooted my PC on 25 Apr. The new version of Aggr loaded OK in Chrome browser but it was changed from ETH to BTC. Clicking the Search (magnify glass) icon does not open a new window.  Not able to change from BTC to another instrument.
Get same result on Firefox browser.
The candle duration icon & settings wheel icon open windows as expected.

The change log does not mention V 3.1.0

Thank you,
Steve
...

**Comment by Tucsky** [comment]
Looking into it,
Can you please export your db and upload it here

**Comment by sfroach** [comment]
Thanks for response.
I do not find an Export db in app settings.
Please provide me some instructions on how to export the db.
I'm running aggr on Chrome browser windows 10 PC.
Thanks

**Comment by Tucsky** [comment]
@sfroach 
Tbf this might not be very usefull because you said you tried on multiple browser so it's might not be template related issue, but let's try anyway. here is how to export the local aggr db:
https://user-images.githubusercontent.com/5738336/165617545-72c35392-10cd-4174-af50-5ed361fca767.mov

nother thing to try is to see if there is anything in the console tab of the chrome dev tool
- right click on the site + inspect element to open
- then go console tab
- then try to open the search window and see if there is any red in the console

**Comment by sfroach** [comment]
Where will I find the Settings > Reset > export  aggr db file?
user files? program files?

Aggr > inspect > console > scn prt

**Comment by sfroach** [comment]
Aggr > Inspect > Console  
results are in red...
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
aggregator.fcc6aa55.worker.js:1 WebSocket connection to 'wss://ftx.com/ws/' failed:
value @ aggregator.fcc6aa55.worker.js:1
aggregator.fcc6aa55.worker.js:1 Uncaught (in promise) undefined
aggregator.fcc6aa55.worker.js:1 WebSocket connection to 'wss://stream.bybit.com/realtime_public' failed:
value @ aggregator.fcc6aa55.worker.js:1
aggregator.fcc6aa55.worker.js:1 Uncaught (in promise) undefined
aggregator.fcc6aa55.worker.js:1 WebSocket connection to 'wss://stream.bybit.com/realtime' failed:
value @ aggregator.fcc6aa55.worker.js:1
aggregator.fcc6aa55.worker.js:1 Uncaught (in promise) undefined
aggregator.fcc6aa55.worker.js:1 WebSocket connection to 'wss://www.deribit.com/ws/api/v2' failed:
value @ aggregator.fcc6aa55.worker.js:1
aggregator.fcc6aa55.worker.js:1 Uncaught (in promise) undefined
gvaw:1 Refused to execute script from 'https://charts.aggr.trade/js/chunk-85145916.173a1a66.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
app.fb23c6bc.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk chunk-85145916 failed.
(error: https://charts.aggr.trade/js/chunk-85145916.173a1a66.js)
at Function.s.e (app.fb23c6bc.js:1:977)
at t.value (app.fb23c6bc.js:1:97607)
gvaw:1 Refused to execute script from 'https://charts.aggr.trade/js/chunk-85145916.173a1a66.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
app.fb23c6bc.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk chunk-85145916 failed.
(error: https://charts.aggr.trade/js/chunk-85145916.173a1a66.js)
at Function.s.e (app.fb23c6bc.js:1:977)
at t.value (app.fb23c6bc.js:1:97607)

**Comment by sfroach** [comment]
Hello,
I updated Chrome to latest.
Aggr v3.1.0  27Apr.

Aggr Search icon is now working as expected = issue fixed.

Thanks much

**Comment by Tucsky** [comment]
Yeah I was about to say, it just look like cache issue ..

With that sorted, if you still see this :
![image](https://user-images.githubusercontent.com/5738336/165641696-fd372573-d7dd-424d-9c1e-8ae5f890305f.png)
,then I believe it could be an adblock preventing aggr from connecting to exchanges api.
So if you never see bybit / ftx or deribit trades in the feed just try to disable your Adblocker for this site! There is no ads anyway 😄
