### ISSUE TITLE
V3 - Audio sometimes glitche and crashes, need to turn audio off and on to make it work

### ISSUE THREAD

**Issue by test1101111** [Tucsky/aggr#21]
Hello.

As in title. Idk if this is only my machine, but couple of times I've noticed that on relatively big nr of liquidations the audio first glitches for few seconds and then crashed and we can not hear anything. Switching the audio off and on in setting repairs it.

Win 10 64 bit, Chromium

Btw, using the occasion - how can I backup my settings from the json file that I've created before?

**Comment by Tucsky** [comment]
Please backup workspace (settings ->  workspace -> 3 dots button -> download)
Then share it here so I can test your settings.

Also after doing the backup, please try reset your audio settings (trade pane settings -> audio threshold -> presets -> apply default) for every trades panes you have. See it that fixes it

**Comment by Tucsky** [comment]
I believe this was a temporary issue, I never experienced this so i'm just going to close this now
In case it happen again :
![image](https://user-images.githubusercontent.com/5738336/124027226-ec9da700-d9f2-11eb-8910-3b0ca588e7d7.png)
