### ISSUE TITLE
please add options to config header for "embed website", especially "User-Agent".

### ISSUE THREAD

**Issue by enel1jk** [Tucsky/aggr#212]
Thanks for sharing your ideas! Make sure you have searched for similar request using the search feature before submitting!!
Requests related to orderbook, open interest or any futures related data will be rejected!

It's very clever to add a type of panel that contain "embed website", that makes many things possible. 
But the size of panel can't as big as normal, because there will be not only one panel. At the same time, there are many websites adaptive by "User-Agent", they can output a mobile website, that's what more appropriate for a panel.

So, can we options to config header for "embed website", especially "User-Agent"?

p.s. Forgive my poor English. 😂

**Comment by Tucsky** [comment]
This is not possible because of cross-origin policy sorry :(

Added a feature to zoom in and out, so there is that at least :)
