### ISSUE TITLE
Please add timestamps to the chart

### ISSUE THREAD

**Issue by whyCPPgofast** [Tucsky/aggr#219]
It would be very nice to see timestamps when hovering on the chart (all timeframes). Preferably `2022-05-14T00:00:00.000Z` format.

**Comment by Tucsky** [comment]
why

**Comment by whyCPPgofast** [comment]
If I look at the chart and scroll back I have no idea at which point in time that bar rendered. Unless I literally count all of the bars up to that point which is obviously not gonna happen. Also a chart without an X axis label just looks weird.

**Comment by Tucsky** [comment]
Pretty sure the x axis is there, maybe it's below the view port ? try scroll the page and bring the chart back up so that the bottom side is visible at all time

![2022-05-15 11 55 26](https://user-images.githubusercontent.com/5738336/168467117-9e4d69d6-4001-4ab0-ae17-6f3e0a9b5005.gif)

**Comment by whyCPPgofast** [comment]
holy shit im dumb
