### ISSUE TITLE
Saving changes on webversion

### ISSUE THREAD

**Issue by Jaakuice** [Tucsky/aggr#22]
Hi,
Im using the new updated webversion, i have changed a few things and most of them have changed and continue after a session change. I cant manage to get the BTCUSD(SPOT) pane to save any changes. I added a new threshold and edited the colours. The change happens but like i say doesn't change. Saving a preset  and trying to load also doesn't work.
Also with the same pane the show both trades and liquidations does't seem to show any liquidations.

**Comment by Tucsky** [comment]
Thank you kind sir for the report. 
This is confirmed bug
