### ISSUE TITLE
"Slider for the selected exchange"

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#229]
Hello, I see that you updated today. But I think that the slider for selected exchanges has not been removed. Can you add it again?
I had various exchanges set up for the yearly sum

**Comment by Knf69** [comment]
![image](https://user-images.githubusercontent.com/100996537/180412408-cef4a41d-54ec-44e1-85ee-1094730aa558.png)

**Comment by Knf69** [comment]
I want it to be like before the Update that I can, for example, add coinbase from 2 million and bitfinex from 3 million,, and now everything is from one sum :(

**Comment by Knf69** [comment]
You cannot see the slider / bar to move from the size of the given exchange you want to see. It is very important to me and my team. please add it again

**Comment by Tucsky** [comment]
it is back but not a very useful feature imo, bloating the ui a lot

**Comment by Tucsky** [comment]
i put it back for the old trades feed, the new one won't have it
if you wanna add different threshold within a feed might as well do it in a different feed

**Comment by Knf69** [comment]
I find this a very useful feature. Thanks for bringing me back :)
