### ISSUE TITLE
Rekts No Work

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#230]
I noticed that the Rekt is not working at all after yesterday's Update,I noticed that the Rekt is not working at all after yesterday's Update.

![image](https://user-images.githubusercontent.com/100996537/180599331-2b0d73ee-9afb-4ebb-a7c9-e452f0a66435.png)

Last hour of liquidation

![image](https://user-images.githubusercontent.com/100996537/180599312-7dd898f1-c0f9-4ad0-802d-4642b2d3a338.png)

**Comment by Knf69** [comment]
Me and my group see more bugs on V3 Aggr. Write to me on discord it will be better communication :)

**Comment by Tucsky** [comment]
Liqs a showing for me ... template file would help @Knf69 ;)

**Comment by maestrolol** [comment]
Here also don't work, please help!

**Comment by Knf69** [comment]
@Tucsky The problem with rekts is still there. once it works once it doesn't work please do something about it.
in the morning it showed me normally and now it has been showing nothing for 2 hours. I checked it on 3 computers

**Comment by Knf69** [comment]
microsoft Edge browser, The Liq still does not work on 3 computers

**Comment by Tucsky** [comment]
Just tried on ms edge and the liquidations appeared as expected :)

https://user-images.githubusercontent.com/5738336/183881533-6ad93083-8e80-459a-96e4-bdf8318dda70.mov
