### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#232]
Why is it showing me the normal color once and then flashing,?This flashing color is annoying.

https://cdn.discordapp.com/attachments/989482076833218590/1001583980442820799/unknown.png

https://gyazo.com/84e230e8b2bf1a2323265a652751e95e

**Comment by Knf69** [comment]
15 minutes later it shows the normal color and I have not changed anything in the options
https://cdn.discordapp.com/attachments/821818679532191796/1001587311429029968/unknown.png

**Comment by Tucsky** [comment]
What do you mean by flashing ?

**Comment by Knf69** [comment]
https://i.gyazo.com/737f4bc1fda733f74f2a7cd09c8cc6c7.mp4

W ustawieniach mam klikenite off "Ul animations are Enabled" why these colors keep flashing in the background?
 @Tucsky

**Comment by Tucsky** [comment]
The gifs you mean ? if you refresh the page after ticking / unticking the Ul animations option it will apply
