### ISSUE TITLE
Odd Data from Bitmex

### ISSUE THREAD

**Issue by abn2609** [Tucsky/aggr#236]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- [ ] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
- [ ] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
- [x] I documented the issue with screenshots
- [ ] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue
At 06:00:29 UTC time (just within hour of posting), I saw a pop higher in ETH which I have posted a screenshot and I noticed the data coming from Bitmex looks inaccurate to say the least, unless $98B was actually traded at that price. Not sure what is happening here but worth a look into their data feed.

![image](https://user-images.githubusercontent.com/63540969/185053698-3db6c984-3afb-4c36-9dc4-6eece11b4de8.png)

Thank you all!
...

### Steps to reproduce

(Preferably from a clean environment / incognito mode)
1. TODO
2. TODO
3. TODO
...

**Comment by Tucsky** [comment]
Hi, the old app is not maintained anymore
If you don't want to use the new one, you can make the change in this file https://github.com/Tucsky/SignificantTrades/blob/master/src/exchanges/bitmex.js
to match the new formulas 
https://github.com/Tucsky/aggr/blob/master/src/worker/exchanges/bitmex.ts
And use it locally
