### ISSUE TITLE
[DATA] Add OKEX / DYDX liquidation

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#237]
is it possible to add these 2 exchanges for liquidation Okex/Dydx?

**Comment by Tucsky** [comment]
👍🏼  dydx liqs will be added next release

for okex I would if I could, however they never exposed the info through websocket api, only rest api which is not possible to use client side

**Comment by Knf69** [comment]
Thanks so much for the information. Have a nice day!

**Comment by Knf69** [comment]
@Tucsky Hi, work is underway on adding it, is it possible?

**Comment by DerivaTrivia** [comment]
Is this dude just looking at the charts?  Against his DeepMind trading can i show data, to accumulate my profit?  Is there any good  script do this?

**Comment by Knf69** [comment]
@Tucsky When addy Dydx?

**Comment by adeacetis** [comment]
@Tucsky did add a liquidation level for DYDX, but we wont do OKEX because their API doesn't offer the data via WebSocket.

Closing this issue.
