### ISSUE TITLE
Alert for Counters Volume

### ISSUE THREAD

**Issue by ChicodelMar** [Tucsky/aggr#238]
Hello, its possible to add an Alert in the Pane "Counters".

I want to trigger the Value, would be nice to have a Integration to Telegram Alerts.

For Example
Timeframe "1m"
 "Alert 1" all Orders above 10.000.000 $ sell
 "Alert 2" all Orders above 10.000.000 $ buy

![vol](https://user-images.githubusercontent.com/90317446/185314575-28e4f2d4-65a2-4860-a40d-7f2e1c9ac1bd.png)

**Comment by adeacetis** [comment]
This is replaced with #315
