### ISSUE TITLE
Problems running npm install Ubuntu 22.04

### ISSUE THREAD

**Issue by icazaji** [Tucsky/aggr#240]
Hi, Thanks for your good work I have try to install Aggr in a ubuntu 22.04 following your instructions but all time get this errors:

/Aggr/aggr$ npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN old lockfile fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (/usr/share/nodejs/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/share/nodejs/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:759:9)
npm WARN old lockfile  Could not fetch metadata for fork-ts-checker-webpack-plugin-v5@5.2.1 fork-ts-checker-webpack-plugin-v5: No matching version found for fork-ts-checker-webpack-plugin-v5@5.2.1.
npm WARN old lockfile     at module.exports (/usr/share/nodejs/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/share/nodejs/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:759:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '5.2.1',
npm WARN old lockfile   versions: [ '0.0.1-security' ],
npm WARN old lockfile   distTags: { latest: '0.0.1-security' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (/usr/share/nodejs/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/share/nodejs/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:759:9)
npm WARN old lockfile  Could not fetch metadata for vue-loader-v16@16.8.3 vue-loader-v16: No matching version found for vue-loader-v16@16.8.3.
npm WARN old lockfile     at module.exports (/usr/share/nodejs/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/share/nodejs/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:759:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '16.8.3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '16.0.0-beta.5',
npm WARN old lockfile     '16.0.0-beta.5.1',
npm WARN old lockfile     '16.0.0-beta.5.2',
npm WARN old lockfile     '16.0.0-beta.5.3',
npm WARN old lockfile     '16.0.0-beta.5.4'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '16.0.0-beta.5.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.18.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://enterpriserepo.fr.carrefour.com/artifactory/api/npm/one-sma-npm-virtual/vue-svg-loader/-/vue-svg-loader-0.16.0.tgz failed, reason: getaddrinfo ENOTFOUND enterpriserepo.fr.carrefour.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/icazaji/.npm/_logs/2022-08-23T15_46_57_240Z-debug-0.log

**When I run this command**

icazaji@virtual-machine:~/Aggr/aggr$ npm run serve

> aggr@3.2.0 serve
> vue-cli-service serve

sh: 1: vue-cli-service: not found

**Comment by Tucsky** [comment]
I see, try this :

1. remove ./package-lock.json
2. remove ./node_modules/
3. npm install
4. npm run serve

**Comment by icazaji** [comment]
Thanks it is working
I ran twice this commands

npm install
npm run serve

**Comment by Tucsky** [comment]
@icazaji amazing! Thank you for reporting this
I fixed the package-lock to not include the proxy setting which was causing this error so now it's all good 👍🏼
