### ISSUE TITLE
Connect aggr to aggr-server config problems

### ISSUE THREAD

**Issue by icazaji** [Tucsky/aggr#241]
Hi thanks for your time, I have a question
Im trying to connect  aggr to aggr-server I have running both in Windows
![Screenshot_2](https://user-images.githubusercontent.com/10413157/186339950-f7d8301c-0d70-4305-9f4e-3a0df89b9806.jpg)

I created .env.local in aggr root folder but  
![Screenshot_3](https://user-images.githubusercontent.com/10413157/186340521-9bdaf10e-3e5e-4c7a-bec0-fd5632787536.jpg)

But im not sure what your say about this parameters

![Screenshot_4](https://user-images.githubusercontent.com/10413157/186340877-4c06edd9-7b51-400e-a87d-87b77ed2b2a5.jpg)

Can you provide examples of this configuration. Thanks very much by your time

**Comment by icazaji** [comment]
how do you know aggr is connected to the aggr-server

**Comment by Tucsky** [comment]
I see you don't have influxdb on the server side 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/5738336/186381556-f76345ac-f3c9-42ac-a4fb-84d747e06ec8.png">

InfluxDB 1.8 is required for serving preformatted data into a set of timeframe on demand

### - Download and run influx
```
wget https://dl.influxdata.com/influxdb/releases/influxdb-1.8.10_windows_amd64.zip -UseBasicParsing -OutFile influxdb-1.8.10_windows_amd64.zip
Expand-Archive .\influxdb-1.8.10_windows_amd64.zip -DestinationPath 'C:\Program Files\InfluxData\influxdb\'
```

or with docker -> https://hub.docker.com/_/influxdb

you can check that influx is running by navigating to  http://localhost:8086/query
<img width="359" alt="image" src="https://user-images.githubusercontent.com/5738336/186381174-77e39a52-b5da-43a4-a262-24aedd368b0d.png">

then you should see aggr-server connect to it in the logs


### Setting up .env on client
Yours looks ok, maybe you need to specify the timeframes available... not sure
API_URL is the root url of server and shouldn't include anything after the domain:port/  

```
API_URL=http://localhost:3000/
API_SUPPORTED_TIMEFRAMES=10,30,60,180,300,900,1800,3600,7200,14400,21600,28800,86400
```


Hope that help :)

**Comment by icazaji** [comment]
Thanks for your time, I have runnign the influx DB and aggr-server on windows but getting this message
{"code":"unauthorized","message":"unauthorized access"}
![Screenshot_7](https://user-images.githubusercontent.com/10413157/186464791-18eb3a96-00a4-4ea3-896f-6e6fd1100f1d.jpg)

I read is related to some token authentication

**Comment by icazaji** [comment]
sorry I think I installed 2.2 DB im going to try 1.8 version like your link

**Comment by icazaji** [comment]
I thinks is working but I suppose I don't have enough data . There is a way to collect old data?
Check the image says no more data
![Screenshot_8](https://user-images.githubusercontent.com/10413157/186472389-a35de647-5928-48f4-abbd-6b9f8314a6c6.jpg)

**Comment by Tucsky** [comment]
> There is a way to collect old data?

no easy way I'm afraid, especially if you don't know much coding

main purpose of aggr-server is collection and storage in real time, mostly because there is no straightfoward way to download this kind of data (incl. buy / sell volume) for free
Some exchange will let you retrieve tick data from their public API, some don't, some will only allow a day, some only allow 100 trade at a time, some will let you download it from a website (ex https://www.binance.com/en-NG/landing/data) etc... 

Another way is stealing the data from some other platform, like coinalize, tradingview or if you got an account in a private platform like tradinglite, exochart you can try to reverse engineering their api but yeah don't expect me to help you do that lmao

If you have the raw trades files, you can format & import them using the following tool
[importer.zip](https://github.com/Tucsky/aggr/files/9418113/importer.zip) (all instructions are in importer.js)

**Comment by icazaji** [comment]
thanks for your time, im coder, all the purpose of setting all this environment is:
1. Understand the code aggr  and aggr-server
2. I want to create a CVD filtered by trades sizes and exchanges
3. I want to create Open interest graph like the CVD line
4. I want to create funding graph like  CVD line
5. To do all this I need understand the code and some data.

**Comment by icazaji** [comment]
Base on what you explain I will let run the server-all day to collect data and im going to focus
on learn the code to create  the CVD filtered like step 1 
thanks very much

**Comment by icazaji** [comment]
One last questions, how you know the code and the data Do you think it is possible create a CVD filtered by trade sizes?
for example I want a CVD that graph trades from 1 to 10k and other CVD from 10k to 20M usd
