### ISSUE TITLE
Alert push error

### ISSUE THREAD

**Issue by Rajadas** [Tucsky/aggr#242]
When setting an alert an error is displayed:

> **Registration failed - Push service error**
> **You need to make sure your browser is set to allow push notifications.**

My notifications permission is ON

macOs Monterey 12.5.1
Brave latest Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (arm64)

**Comment by Tucsky** [comment]
Don't ask me why but Brave have this feature disabled by default

Just go to brave://settings/privacy and make sure "Use Google services for push messaging" is ON
<img width="672" alt="image" src="https://user-images.githubusercontent.com/5738336/187668967-c91bdd12-891e-42f5-abf2-cafddfac5740.png">

then try again
