### ISSUE TITLE
Huobi feed shows wrong liquidation size

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#244]
Checked on different pages and shows very bad liquidations.
sometimes it shows there is 450k $ long liquidation and there was no liquidation of this size

**Comment by Knf69** [comment]
_
![image](https://user-images.githubusercontent.com/100996537/193029581-2b8d2120-df59-4716-bcf1-7936297a8a45.png)
_
That is the real liquidation of Huobi now.
This is what v33 aggr Huobi shows
_
![image](https://user-images.githubusercontent.com/100996537/193029865-d8a5db23-968c-4960-ab6a-6fa236ad03a6.png)
_

**Comment by Knf69** [comment]
It shows quite different v33 agrr

**Comment by Tucsky** [comment]
I just checked and it the numbers are looking good
![image](https://user-images.githubusercontent.com/5738336/193033815-7e1a7dff-3bc4-4278-9f6b-e7b625647bbd.png)

**Comment by Tucsky** [comment]
tho 154.6k at 14:17 (GMT+2) on your screenshot is not. 
template might help to see what the issue is

**Comment by Knf69** [comment]
Yes, but as I have 1000 ms agg set. That's when I see more spot / perp orders
_
![image](https://user-images.githubusercontent.com/100996537/193328089-aec37d26-0667-4363-8716-3b66f4e6bd3f.png)
_

**Comment by adeacetis** [comment]
If the problem occurs again, feel free to reopen this case.
