### ISSUE TITLE
Duplicate windows Problem

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#245]
## Describe the issue
Hello, I can see there is a problem with the "duplicate window".
If I want to duplicate the window, it shows me the new settings, not those that I have saved from the size of the item.I remember recently it was normal and now it is different

## Steps to reproduce
(Preferably from a clean environment / incognito mode)

TODO
TODO
TODO ...

**Comment by Knf69** [comment]
@Tucsky

**Comment by adeacetis** [comment]
I have reformated your original post, please edit it and add the steps to reproduce this behavior.
Adding annotated screenshots could help as well.

**Comment by Tucsky** [comment]
I believe this was fixed last month ✅
Feel free to reopen if needed
