### ISSUE TITLE
question: how does the slider work? (threshold slider) it aggregates or filters out

### ISSUE THREAD

**Issue by KamelittaOida** [Tucsky/aggr#247]
hello
does it reject lower trades or does it aggregate them into a package?

**Comment by adeacetis** [comment]
The slider modifies the thresholds by some coefficient. It's a way to modify all values quickly.

1. Open the Trade pane settings.

   You should see the slider on top with Thresholds section below like so:
   
   ![image](https://github.com/Tucsky/aggr/assets/20586054/feebcfaa-7594-415f-a7df-b30577c25239)

2. Slide the cursor to the right.

   All thresholds are bigger. It now filters out all the trades that are smaller than 380k. You can edit visual effect for each level in this dialog.

   ![image](https://github.com/Tucsky/aggr/assets/20586054/4489271e-50a2-4ba7-8a86-feb445c8edff)
