### ISSUE TITLE
Script Question

### ISSUE THREAD

**Issue by pattty847** [Tucsky/aggr#249]
Hello again, 

I'm just trying to make a script and I seem to be stuck on the last two wt1/wt2.

```
src = (($price.high + $price.low + $price.close) / 3)
esa = ema(src, 9)
de = ema(Math.abs(src - esa), 9)
ci = (src - esa) / (0.015 * de)
wt1 = ema(ci, 3)
wt2 = sma(wt1, 12)

line(wt1, color = 'green')
line(wt2, color = 'green')
```

It seems that the wt1, and wt2 do not do anything. I have ran `console.log` on `ci, de, esa, src` and they all have values but `wt1/wt2` are labeled NaN. I get no errors after saving either. 

Maybe you should also create a Discord too, Tucsky! I'm sure tons of ppl would join.

![Screenshot 2022-09-28 184751](https://user-images.githubusercontent.com/23511285/192902046-c67a06b2-cfee-4f77-acb7-93672d3bb84a.png)

**Comment by Tucsky** [comment]
looks like `de` can be 0 in your script
dividing by 0 lead to NaN (not a number) which doesnt work on the chart

`ci = (src - esa) / (0.015 * (de || 1))`

scripting is very raw... and does not have much verifications to prevent too much performance impact

so to debug the script you can use your browser dev tool, and type "debugger" in the script code
![image](https://user-images.githubusercontent.com/5738336/192904495-dddbd192-7397-4630-9774-59c2ea1206f3.png)
although variables will have different names, it can help understanding the why it's not printing anything :)

wrap it in a condition like `if (!src) debugger` at the very beginning of the script to ensure the breakpoint will be active before the first bar is rendered (click in and out the code box to re render all bars)

**Comment by pattty847** [comment]
> 

Bless Tucsky. Thanks for your help again. 

Question: So, if `de` evaluates to 0 it will use 1 instead? Will that effect the output anyway?
