### ISSUE TITLE
Liquidations bug

### ISSUE THREAD

**Issue by elpsykongroo** [Tucsky/aggr#25]
When selecting "Show both trades and liquidations" and liquidations threshold is set lower than trades threshold, any liquidations lower than trades threshold are not shown.

e.g.
I want to see BTC trades higher than 250k and liquidations higher than 50k in the same pane., but only >250k liquidations are shown currently.

**Comment by Tucsky** [comment]
Thanks for the report
I just deployed a fix for this, please let me know If it's ok now ?

**Comment by elpsykongroo** [comment]
All good now.
