### ISSUE TITLE
Bitget Exchanges

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#252]
Do you have any plans to work on the bitget marketplace. More and more popular perp / Spot exchange 80% of my friends are already on it. What do you think about adding this exchange?
It already has a real ftx volume and is still chasing binance perp

**Comment by Knf69** [comment]
Yes, I know I shouldn't be asking this question about adding a stock exchange. But she's really been very popular lately and more and more people are going there. There is a real volume there

**Comment by maestrolol** [comment]
I agree 100%, a lot of volume going through Bitget right now... it would be really nice to have some data from there!

Please add bitget!

**Comment by Bazergji** [comment]
yea i would love it too, since is one of the best exchanges for the moment

**Comment by Lazizo** [comment]
I need this exchange very much because there is a real large volume there,
Write also I have been using this exchange for 4 months and everything is ok

**Comment by LuchinStiglitz** [comment]
i've been using Bitget for a few months and the volume is really large i think the add on aggr is very needed

**Comment by nemanja3** [comment]
Please add bitget.. the volume is much higher than bybit exchange and sometimes even FTX perps.. would be really nice to add confluence

**Comment by Depimioss** [comment]
Please add bitget asap

**Comment by justin929293** [comment]
Please add this exchange, I track all aggr transactions on an ongoing basis, but I miss the bitget exchange I have been a user there for 6 months

**Comment by justjerry1** [comment]
Please add bitget way better than bybit

**Comment by Knf69** [comment]
@Tucsky Hi, as you can see, the interest in this market is very high. You can check its btc usdt / btc usd volume yourself. It is real and very big. Think about adding this perp/+ Spot exchange Bitget. we will be very thankful. 

[
![image](https://user-images.githubusercontent.com/100996537/194086787-07e51825-dc10-4b19-ab8f-21ae99cb4e58.png)
](url)

**Comment by Tucsky** [comment]
Hello,
Thank you for the suggestion,
However I do not plan to add Bidget, nor that I plan doing any active development on this project at the moment.
That said, if you are willing to contribute and share your work on the matter in a pull request... PR will be merged

**Comment by Knf69** [comment]
I am very sorry for that. I was hoping that it would be added. it would be the update of the year.

**Comment by adeacetis** [comment]
The data has been added. Closing this issue. Feel free to report if something is wrong.
