### ISSUE TITLE
Coinbase wrong check for sell/buy

### ISSUE THREAD

**Issue by 3Goldjungen** [Tucsky/aggr#253]
in the coinbase.ts onMessage() the current check for sell/buy looks not correct:
`side: json.side === 'buy' ? 'sell' : 'buy'`
should change to:
`side: json.side === 'buy' ? 'buy' : 'sell'`
right?

**Comment by Tucsky** [comment]
Unlike their competitors, Coinbase reports "matches" : limit orders filled by market order and in that object `json` the side is the maker. 
Aggr feed shows the takers (market orders).
