### ISSUE TITLE
Hotkey / button for removing all price lines

### ISSUE THREAD

**Issue by VIEWVIEWVIEW** [Tucsky/aggr#254]
**Is your feature request related to a problem? Please describe.**
I often make countless lines for alerts when trading on very low time frames. I'd like to remove them all, when I'm coming back in a later session.

**Describe the solution you'd like**
A button or hotkey to remove all lines on the chart when it becomes too cluttered.

**Describe alternatives you've considered**
Saving a template and then loading it later again. Well, it's too much effort compared to a single button press imo.

**Comment by Tucsky** [comment]
Good idea 👍🏼

**Comment by Tucsky** [comment]
I added a context menu with easy access to chart's alerts
![2023-03-15 20 10 53](https://user-images.githubusercontent.com/5738336/225417973-ce89db59-6be0-4db6-8591-9c220a46026c.gif)

**Comment by VIEWVIEWVIEW** [comment]
Ah, I see flip was added too! Awesome!

Btw, how do you create these alerts instantly? The latest version seems to open an emoji/alert name window first

**Comment by Tucsky** [comment]
I just deployed an update which pass the message popup when "1 click" alert option is enabled. 1min ago
you might want to "hard refresh" the page...

shift + click WILL show the popup, though

just press enter when it shows up :)
