### ISSUE TITLE
Exchanges Rekts

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#258]
Hello, is it possible to add Kraken + Dydx to rekts?

**Comment by lmvdz** [comment]
No Both Kraken and Dydx don't publish liquidations through their API

**Comment by Tucsky** [comment]
Both provide it @lmvdz 
https://docs.futures.kraken.com/#websocket-api-public-feeds-trade
https://docs.dydx.exchange/#initial-response-3

**Comment by lmvdz** [comment]
ahh interesting, I was looking for a liquidation specific subscription
