### ISSUE TITLE
Use setData() to update previous plot values?

### ISSUE THREAD

**Issue by lahomagit** [Tucsky/aggr#259]
Is it possible to update previous data of a plot via the [setData method of the ISeriesAPI](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#setdata)?

This code attempts to draw a horizontal line at the high of loaded data (using a line plot as a priceline, essentially), updating previous values of the line when a new high is found, but it does not work (nor does it throw any error):

```
if(lastTime === 0){

    lastTime = null
    seriesData = []
    theHigh = null
    theBar = null

}

// if new bar and not first bar
if(bar.timestamp % bar.timeframe == 0 && lastTime && bar.timestamp > lastTime){

    (theBar) = {
        time: lastTime,
        value: theHigh
    }

    //push previous bar data
    seriesData.push(theBar)

}

if(!theHigh){
    theHigh = $price.high
}

if($price.high > theHigh){

    theHigh = $price.high

    if(seriesData){

        // update all values in seriesData to new high
        for(let i = 0; i < seriesData.length; i++){
            seriesData[i].value = theHigh
        }

        //update series
        try {
            series[0].setData(seriesData)     
        } catch (error) {
            console.log("error: " + error.message)
        }
    }
    
}

lastTime = bar.timestamp

line(theHigh)
```

**Comment by Tucsky** [comment]
Try one of these

<img width="912" alt="image" src="https://user-images.githubusercontent.com/5738336/198254903-d2cb74c8-e6b4-4c61-895d-c0182eae0339.png">

high of loaded data
[indicator_high-pivot-pivotlength.txt](https://github.com/Tucsky/aggr/files/9878247/indicator_high-pivot-pivotlength.txt)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/5738336/198255046-3ee19fd7-ea82-4f4f-a57e-3916bc600ba4.png">

high found in the last n bars
[indicator_high-line.txt](https://github.com/Tucsky/aggr/files/9878248/indicator_high-line.txt)

**Comment by lahomagit** [comment]
The pivots example is excellent, thank you. Is there any way to make it automatically draw new pivots as data is added to the chart? Right now it seems to require toggling the indicator to redraw with new data, and I haven't been able to solve that.

**Comment by Tucsky** [comment]
You are right there was a bug in the script :)
Fixed it here with option to use body of candle instead of wicks 👍🏼 
![2022-11-14 11 06 24](https://user-images.githubusercontent.com/5738336/201633047-27febbf9-e09c-45f1-b925-776194d4440e.gif)
[indicator_high-pivot-pivotlength copy 1.txt](https://github.com/Tucsky/aggr/files/10001904/indicator_high-pivot-pivotlength.copy.1.txt)

**Comment by Redline600** [comment]
Invalid input for function brokenarea, expected 2 arguments (lowerValue and higherValue).       Dude, I'm getting such an error, I haven't been able to solve it for 2 days, can you help me? Can you give me this code working. please i need this

**Comment by Redline600** [comment]
yes, I solved the problems myself in my study last night. Can we communicate for different projects?
