### ISSUE TITLE
"Kucoin Exchanges"

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#261]
Hello father, what do you think about the Kucoin stock exchange. The last 3 weeks a very large jump in volume on the spot btc / eth + perp, similar to the volume of the bybit?

Btc Spot
[
![image](https://user-images.githubusercontent.com/100996537/200391672-55ab9f0b-dd3b-46a7-a0bc-3718176f4048.png)
](url)

Eth Spot
[
![image](https://user-images.githubusercontent.com/100996537/200391718-836c32c7-e1a6-42e7-ad80-3e82801cb9ef.png)
](url)

**Comment by Knf69** [comment]
@Tucsky 🙏

**Comment by adeacetis** [comment]
@Tucsky added Kucoin data since you created this post.

Please, test them in the app and report here what you think is missing.
