### ISSUE TITLE
sound  звук

### ISSUE THREAD

**Issue by VitalVolant** [Tucsky/aggr#263]
приветствую.  возможно ли видоизменить звук? 
на  любой другой инструмент или в  наложении  дорожек....
можно из стакана сделать  музыку, в несколько слоёв под настройки стакана цены...
очень хочется увидеть  вкладку инструмент музыкальный  на выбор 
большое спасибо.

**Comment by Tucsky** [comment]
A bit hacky cause you have to use the script but already possible, just drag & drop any audio file in the audio script area, like this :

![2022-11-16 11 14 53](https://user-images.githubusercontent.com/5738336/202153816-f6bbf9f2-4718-411b-8735-86ace6d908e6.gif)

You can combine multiple audio for 1 single buy/sell, apply a delay, change the gain (volume) of the audio

```
  async playurl(
    url?: string,
    gain?: number,
    holdDuration?: number,
    delay?: number,
    startTime?: number,
    fadeIn?: number,
    fadeOut?: number,
    startGain?: number,
    endGain?: number
  )
```

**Comment by Tucsky** [comment]
made a bunch of sounds using Hard Rock Nick's cameos meme last year but lost the files since, was pretty fun

**Comment by VitalVolant** [comment]
спасибо за ответ. 
это безумно круто что вы сделали.
  в том году везде писал по чатам....  и решил только вот написать на прямую...
  
  ! так же пишу и на биржи...  чтоб звук добавили.... !  это очень важная функция.  на мой взгляд. 
  рамок нет. от радио  для слепых....   
  биткоин это жизнь. а  жизнь  и звук++
  
  если увидит не зрячий....
