### ISSUE TITLE
Run problem, string format.

### ISSUE THREAD

**Issue by Merkat81** [Tucsky/aggr#266]
Hi, 
I have git error as you can see below, specifically 

git log -1 --date=format:"%Y/%m/%d %T" --format="%ad 

in vue.config.js while executing

`npm run build`

![image](https://user-images.githubusercontent.com/119469514/204698792-6b07018a-c157-4c9d-9ff4-52b66c91b851.png)

Any ideas?

Thank you in advance.

Ognjen

**Comment by Tucsky** [comment]
the app retrieve the last commit's date when starting
maybe you use different git version so try removing that part or update your git
we use git version 2.33.1

`git --version`

in vue.config.js
<img width="605" alt="image" src="https://user-images.githubusercontent.com/5738336/204764050-6ac2ae80-1206-46a3-87ef-41d3a6353687.png">
