### ISSUE TITLE
Binance Spot Data No Longer Showing Since Their API Change

### ISSUE THREAD

**Issue by solartrans** [Tucsky/aggr#267]
Binance updated their APIs in the past day or so, which included some new geo-restrictions.

It appears Binance spot data is no longer coming through on aggr. Noticed this on BTC and ETH but probably affects others. I have the left column set for spot, and the right for futures. Binance futures seems to be fine, just spot that is not coming through.

Screenshot below. I've heard some folks managed to circumvent this by changing proxies on their API monitoring systems to new regions. Perhaps aggr is facing a different issue though.

![image](https://user-images.githubusercontent.com/26495931/205171261-125b0962-855b-4449-a41b-00cdd0ee90e2.png)

**Comment by Tucsky** [comment]
Someone could make a public server that would act like binance public ws api
To proxy the trades and liquidations

so we could have a set of apis for binance
[
`wss://stream.binance.com:9443/ws`
`wss://backup server 1`
`wss://backup server 2`
...
]

if one is unrechable it would try the second and so on

But we need that someone to share the proxy servers 😄 
so if anyone is interested I can do a simple node script that would get the job done

**Comment by Tucsky** [comment]
@solartrans 
they told me the websocket is not restricted yet but could in the future 
can you share the error from binance api ? maybe your error is something completely unrelated 🤔 

in the dev tool (F12, or Ctrl + Shift + I), either console tab or network tab
<img width="699" alt="image" src="https://user-images.githubusercontent.com/5738336/205279743-ba90ee58-57bf-48fe-a530-a523605633a2.png">

**Comment by solartrans** [comment]
Thanks for looking at this! I didn't realize that you do not have proxies setup on the backend of aggr. The issue was that I am accessing aggr from a US IP, so that's thy Binance were blocking me. Changing to another country's IP has solved the problem. Cheers.
