### ISSUE TITLE
Button to refresh sources

### ISSUE THREAD

**Issue by StijnV007** [Tucsky/aggr#269]
With the current way the sources (pair lists of each exchange) is stored in cache, there's no way to refresh the pair list, other than removing cookies. This is necessary when a new coin is released

Feature request: **Implement a button in the "Add/remove sources" panel to refresh the pair list.** The easiest solution in my opinion would be a "refresh" icon next to the "Toggle grouping" and "Clear" icons.

**Comment by Tucsky** [comment]
This is already implemented :)
If you hover the exchange in the search window
you will see a 🔃 icon
It will query the available products for that exchanges through the proxy server dedicated to caching the result (for 5min)

**Comment by StijnV007** [comment]
Amazing didn't knew of it existence. Thank you for this great tool!
