### ISSUE TITLE
Watermark Settings not available 

### ISSUE THREAD

**Issue by aalhendi** [Tucsky/aggr#27]
### Enable/Disable Watermark functionality
Source Code in ``chartOptions.ts`` Ln 26 ``visible: false,`` Watermark default settings are being exported. The default seems to be false yet watermark still shows by default. The false value is being overridden by ``this.updateWatermark()`` Ln 223 in ``chartController.ts``. 

- [ ] Change ``this.updateWatermark()`` to conditionally run if ``visible`` is false coming in from ``chartOptions``

**Comment by Tucsky** [comment]
Yet another option 😄

**Comment by aalhendi** [comment]
A proposed fix would be something like this in ``chartController.ts``Ln223
```js
if (defaultChartOptions.watermark.visible) {
  this.updateWatermark()
}
```

**Comment by Tucsky** [comment]
defaultChartOptions.watermark.visible is not editable anywhere in the ui atm
which would hide the watermark for everyone and indefinitely

**Comment by aalhendi** [comment]
See PR: #28
