### ISSUE TITLE
Use the REKTS panel with multiples pairs?

### ISSUE THREAD

**Issue by elmagow** [Tucsky/aggr#270]
Hello,

Is it possible to use the REKTS panel with multiple pairs? (or can it be implemented)

I want to get liquidation alerts in the REKTS panel with multiple pairs to get alerts when liquidation happens on the pairs I add, not with just the one on the chart.

Regards

**Comment by Tucsky** [comment]
You absolutely can! Just click on the 🔍 icon and select as many pairs as you want

**Comment by elmagow** [comment]
Oh nice, don't know how I could miss that .. :(
