### ISSUE TITLE
Price drifts over time and corrects when the chart is refreshed

### ISSUE THREAD

**Issue by quadragen** [Tucsky/aggr#271]
This issue seemed to coincide with Binance disabling access to their websocket in the USA, although I am not certain how or why.  Since Binance made this change, over the course of an hour or more, the price on the chart will begin to drift up or down more and more.  The price will be $10 off, then $20, then $30, and so on.  Clicking the magnifying glass on the chart, and then pressing REFRESH corrects the price.  This has to be done once every hour or so but it varies.

This may only be occurring when accessing the chart in the US due to the Binance restriction.

**Comment by Tucsky** [comment]
You are right, use a vpn or disable all binance pairs from the app. When you refresh the chart / load the app the data initially come from aggr server **then it connects to the exchanges for realtime data**, so if Binance blocks you, price for BINANCE:btcusdt, BINANCE_FUTURES:btcusdt etc won't get updated so the average becomes more and more wrong as time goes,
Aggr is probably useless to US users now but it is what it is.

**Comment by quadragen** [comment]
Even when turning the binance pairs off nothing seems to change. Sent from my iPhoneOn Dec 18, 2022, at 6:47 AM, Tucsky ***@***.***> wrote:﻿
You are right, use a vpn or disable all binance pairs from the app. When you refresh the chart / load the app the data initially come from aggr server then it connects to the exchanges for realtime data, so if Binance blocks you, price for BINANCE:btcusdt, BINANCE_FUTURES:btcusdt etc won't get updated so the average becomes more and more wrong as time goes,
Aggr is probably useless to US users now but it is what it is.
