### ISSUE TITLE
what is sound effect on website?

### ISSUE THREAD

**Issue by efeint01** [Tucsky/aggr#272]
hello, maybe this question can be considered absurd. 
but where can I find the .mp3 file of the sound effects playing on the site?

**Comment by efeint01** [comment]
I know the audio is generated dynamically, but is it taken from any .mp3 file?

**Comment by Tucsky** [comment]
That's a good question actually. Sound effects are 100% generated by default. It's just frequencies. But you can use your own mp3/wav/ogg audio file if you want

**Comment by efeint01** [comment]
Thanks. Can you share the method you used to create the sound? what are frequency settings

**Comment by Tucsky** [comment]
Sure, it's all [here](https://github.com/Tucsky/aggr/blob/master/src/services/audioService.ts)

For the most part it's a combination of sine wave audio signals that goes through Tuna.js to make it easy on the ears / more sophisticated
The gain used for each sound is relative to the `trade volume` / `significant trade volume`
