### ISSUE TITLE
Kraken+Liq some exchanges

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#273]
Hello, is there any way to add Kucoin Perp/Futures to v3 Aggr?. Spot view works very well, you can see everything 👍 
But there is also a lot of Perp/Futures Kucoin missing

I also wanted to ask if adding Liq Kraken/Kucoin/Phemex/Okex. 

Okex+Kucoin would be the most important because there is a gigantic volume there 💯

**Comment by Knf69** [comment]
@Tucsky ?

**Comment by adeacetis** [comment]
Kucoin Perps/Futures have been added already

Liquidation isn't possible with the current state of the project.
