### ISSUE TITLE
Connection Issue???

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#274]
This bug keeps popping up for me

I don't use any proxy and no antivirus blocks this site. Why do I have this message all the time?

[
![image](https://user-images.githubusercontent.com/100996537/212470838-93104bce-0277-495d-b1b2-952b8c27a063.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/212470844-34d3af24-d795-4efb-a15d-f6b115cc409b.png)
](url)

**Comment by musicims** [comment]
Same issue but on many other exchanges

**Comment by Tucsky** [comment]
That message was added so you don't keep exchanges that you can't connect to which cause data inconsistency (you get the data from the past via aggr historical services but can't see realtime data)

> Same issue but on many other exchanges, been happening for a few days now


Nothing changed in the way you connect to exchanges, it's just a way to inform that you aren't getting realtime updates from it

I can't change the fact that you are located in the US, but I can inform you that you won't get realtime updates from that problematic exchange

For Kraken it's a little bit different tho, as it goes down pretty often but is only temporary
You can always click the dismiss button to never see that message again for that specific exchange API.
