### ISSUE TITLE
Historical price data

### ISSUE THREAD

**Issue by LucaPaull** [Tucsky/aggr#275]
Hello, why can't I see the historical price chart anymore?
I would really appreciate your help :)
![Historical_Price](https://user-images.githubusercontent.com/122698451/212494343-e3f260e0-12b3-47a1-a471-dde1210e6daa.jpg)

**Comment by wafer5** [comment]
same problem since yesterday. look like data resetting every 24 hours.
also having connections issue error, multiple EX. test with VPN doesn't show any error. (I'm from Iran)

**Comment by Tucsky** [comment]
hosting provider reported ddos on the server earlier this week, since then database died, server rekt.
DB backup won't load, it's a know issue on influxDB but won't be fixed cause old version
No sure what do

**Comment by LucaPaull** [comment]
Ah Okay thanks for the reply

**Comment by LucaPaull** [comment]
Was just wondering but as long as the price now is acurate im good

**Comment by thechainer** [comment]
This is too bad mate. I was building a trading strategy based on the data there. all gone now :(

**Comment by LucaPaull** [comment]
On coinalyze you can find most of the same Data I think. aggr is just better looking in my opinion :)

**Comment by LucaPaull** [comment]
Historical Price Data is back up for me at the moment maybe for you too

**Comment by thechainer** [comment]
It is better but unfortunately I just can see from the November 1st to now if I choose 30m to 4 Hour time frame. If I choose 4hour or higher time frame, the data starts from May 2022. Thank you for your advise. Coinalyze doesnt support custom indicators :/ I dont understand who does such stupid things. @Tucsky I cant fund the project or I cant help with coding but if there are another ways to support the project I am a volunteer. And thank you for creating and sharing this great tool with us. Cheers

**Comment by Tucsky** [comment]
@thechainer thanks man ! I appreciate it.
I will try add a little bit more candles to the higher timeframes.

**Comment by adeacetis** [comment]
Can we close this issue @thechainer and @LucaPaull ?

**Comment by LucaPaull** [comment]
Yes sure. Thanks a lot!
