### ISSUE TITLE
Error Site

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#276]
This bug keeps popping up for me

[
![image](https://user-images.githubusercontent.com/100996537/212945208-239338ae-189b-434c-8523-bc44906a4b2d.png)
](url)

**Comment by Knf69** [comment]
I've seen this message 20+ times today

**Comment by Tucsky** [comment]
Click dismiss ? or remove all connections to that exchange
I explained [here](https://github.com/Tucsky/aggr/issues/274#issuecomment-1383867173) why you shouldn't keep an exchange if they blocked your ip
