### ISSUE TITLE
Change chart crosshair line(s) color/style/width

### ISSUE THREAD

**Issue by lahomagit** [Tucsky/aggr#278]
Is it already possible to change the color/style/width of the chart crosshair lines and I'm just missing it? If not, I'd love such a feature. It's quite hard for me to see at the moment.

**Comment by Tucsky** [comment]
Theres a lot of options but not this one sorry
just made it brighter is it ok now?

**Comment by thechainer** [comment]
wow crosshair syncing is really great. thank you :)

**Comment by lahomagit** [comment]
Much better now!  Thank you. And agreed, crosshair syncing is wonderful.
