### ISSUE TITLE
Duplicate Windows

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#283]
Can you change this duplicate?
If I take a new duplicate window, the settings show the new ones, not the old ones that I had saved?

these are my current settings for btc
[![image](https://user-images.githubusercontent.com/100996537/220126384-01458840-3144-46de-9301-b909619c6478.png)
](url)

and this is how the window will look when you click duplicate
[
![image](https://user-images.githubusercontent.com/100996537/220126662-5c707b61-c34a-4097-81da-74bede37a8fa.png)
](url)

the point is that I want to remove the perp and leave the spot on the same page. So that, for example, there would be a spot and perp orders would appear again, it used to be like that with duplicak, when you pressed it, old records appeared, and now it is different

**Comment by Knf69** [comment]
@Tucsky Hmm?

**Comment by Tucsky** [comment]
@Knf69 seems to be fixed now. sorry about that!
