### ISSUE TITLE
sound pitch

### ISSUE THREAD

**Issue by OutOfThisPlanet** [Tucsky/aggr#284]
I've checked out the new app and it looks awesome! 

Good work!

I keep going back to the old charts though, because of the audio pitch shift option. I couldn't find it on the new version...

Am I blind, or is it missing?

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/221498564-d4c60058-14fb-411a-ac1c-f85e1691f50e.png)
It's called transpose now! sorry for the confusion 😃
