### ISSUE TITLE
Rekts/Liq

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#285]
Hello, I have a question because I follow bitget/kucoin spot/perp/rekts. Spot doesn't work bitget, very strange that it does not show spot Bitget, liquidation bitget doesn't show either. It's the same with kucoin rekt not showing up.  On bitgert kucoin + okex is the same problem with it not showing liquidation?

Thanks for adding the Bitget+Kucoin perp!

**Comment by adeacetis** [comment]
Since your post, the data from Kucoin and Bitget have been included. However, there is no feed available for liquidation or "rekt" events from these exchanges, and the same is true for OKEX.

**Comment by Knf69** [comment]
Ok thanks for answer :)

**Comment by adeacetis** [comment]
OKEX API's documentation is very slow. There must be some leak. Eventually, I could find a REST API offering liquidation for futures/perps:
Documentation:
https://www.okx.com/docs-v5/en/#rest-api-public-data-get-liquidation-orders
Webpage
https://www.okx.com/trade-market/liquidations/swap

**Comment by Tucsky** [comment]
REST but not websocket, so client cannot get them due to cors issue
Closing now but feel free to reopen when OKEX releases a ws channel dedicated to those liquidation orders
