### ISSUE TITLE
Historical data missing on 10s charts

### ISSUE THREAD

**Issue by deandreee** [Tucsky/aggr#286]
Hi, this is more of a question, but I noticed recently (~week) that basically all alts are not loading any chart history for 10s charts. BTC and ETH both still have it, but for others it's empty.

Am I doing something wrong maybe? Was the 10s historical data disabled on purpose? Any plans to bring it back?

Thanks!

**Comment by adeacetis** [comment]
Hey,

@Tucsky recently changed WebSocket library and it broke broadcast mode, I wonder if this is related.

If he deployed the latest 'master' in production this as surely broken something if still used.

I am currently working on a fix - not easy - but I would need some guidance about the testing protocol.

Cheers.

**Comment by Tucsky** [comment]
It's not related, I disabled sub 10s and 30s for alts to free up some memory on the server
alts consist of 95% of the data injested yet nobody use them lol

Ill fix broadcast mode tho thanks for letting me know! :)

**Comment by adeacetis** [comment]
> It's not related, I disabled sub 10s and 30s for alts to free up some memory on the server
> alts consist of 95% of the data injested yet nobody use them lol I'd rather have more markets available but no second chart on those alts
> 
> Ill fix broadcast mode tho thanks for letting me know! :)
> 
> 

Can I help you with that and you'll review it?
What do you think?

I also have a bunch of PRs opened on the repo and would like to do more. Did send you an email about this? It was in French.

Did you see it?
