### ISSUE TITLE
wrong price chart

### ISSUE THREAD

**Issue by wafer5** [Tucsky/aggr#287]
hi, my chart price it's not correct.
![aggr](https://user-images.githubusercontent.com/111606691/224475278-6f58b5cb-e6b1-444a-b43d-ab94c5bec7a5.jpg)

**Comment by Tucsky** [comment]
Hi! My guess is that you have more than btc on that chart
You can see which markets it is watching by clicking the 🔍 icon
or export the template and drop it here so I can take a look

**Comment by wafer5** [comment]
> 

no. it's just btc. it's was ok until few hours ago.
i sent you email.

**Comment by Tucsky** [comment]
Oh ok so that price is correct, just that you added a whole lot of usdc quoted btc markets on that chart, and due to the depegging event on the USDC, markets quoted in USDC are pumping.

**Comment by wafer5** [comment]
i have another question on price script said "plotcandlestick(avg_ohlc(bar))" . can i have just binance price and not average?

**Comment by Tucsky** [comment]
You can recreate that `bar` variable with only BINANCE:btcusdt inside
```javascript
candlestick(avg_ohlc({
  localTimestamp: time,
  sources: {
    'BINANCE:btcusdt': BINANCE:btcusdt,
  }
}))
```
