### ISSUE TITLE
Adding more Raw Insider Metrics Data, please?

### ISSUE THREAD

**Issue by DROBNJAK** [Tucsky/aggr#292]
Raw Insider Metrics, unadulterated by statistic, is pure predictive gold as far both discretionary and algorithmic trading.

You've got Cumulative Volume Delta ( CVD ) and Liquidations so far, which is just phenomenal. 

But could we please have the other important ones, like:

- Funding Rate
- Open Interest
- ... and any other you can pull

Actually, just for inspiration, here are insider metrics other sites are pulling:

https://www.binance.com/en/futures/funding-history/perpetual/4
https://hyblockcapital.com/#video
https://stats.gmx.io/
https://coinalyze.net/bitcoin/open-interest/
https://cryptoliquiditymetrics.com/

It would be phenomenal if we could possibly have more of those?

**Comment by Tucsky** [comment]
I know sir, there are countless request for this already.
Unfortunately two things are preventing me to integrate those: time and money

But I'm grateful for the time you took out to write this feedback as always ✌🏼

**Comment by DROBNJAK** [comment]
Sure, you are already doing a phenomenal job.

Why do you need money? Do you need to pay for crypto data-feeds?

**Comment by Tucsky** [comment]
Because time is money good sir
