### ISSUE TITLE
Mexc exchange

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#293]
Hello, what do you think to add a new exchange very popular and fast growing "Mexc Globa"?

**Comment by Tucsky** [comment]
Yes sir

**Comment by Knf69** [comment]
@Tucsky hmm, the stock exchanges do not show mexc global yet, whether everything is fine with me or is the work in progress?

[
![image](https://user-images.githubusercontent.com/100996537/227718545-d5648ca8-4c33-4daf-8fad-57b470224239.png)
](url)

**Comment by Tucsky** [comment]
It's still in testing phase along with some other feature on https://tucsky.github.io/aggr

**Comment by Knf69** [comment]
> It's still in testing phase along with some other feature on https://tucsky.github.io/aggr

Oh thank you very much and best regards :)

**Comment by Knf69** [comment]
> It's still in testing phase along with some other feature on https://tucsky.github.io/aggr

I only watch mexc, but something stinks to me that volumen there, 

[
![image](https://user-images.githubusercontent.com/100996537/227726937-c3b06a1c-145c-4bbd-8d8b-34e4df948d90.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/227726988-4bb3ebee-5080-479a-8402-f5977cc8bf5f.png)
](url)

Volumen do not agree with this at all from their official website and orderbook

**Comment by Tucsky** [comment]
Oh shit haha this is a precious feedback 🙏🏼.
Would you mind sharing which contract on mexc you looking at here ?

**Comment by Tucsky** [comment]
@Knf69 I fixed it on the test environement

**Comment by Knf69** [comment]
> Oh shit haha this is a precious feedback 🙏🏼. Would you mind sharing which contract on mexc you looking at here ? @Knf69 EDIT: nvm I see it as well. working on it
Usd ;]
I check if everything is perfect from their website I will let you know :)

**Comment by Knf69** [comment]
I'm watching right now and I can see I agree perfectly with their side

[
![image](https://user-images.githubusercontent.com/100996537/227736118-6d0b84f5-41c4-4083-9053-5e28b23f8926.png)
](url)

[https://cdn.discordapp.com/attachments/1057614148822892639/1089261367640477717/42f9e531147c7f117983067b80ee435c.png](url)

**Comment by Knf69** [comment]
I see now that everything agrees that the site is perfect

[
![image](https://user-images.githubusercontent.com/100996537/227736321-be1e82f1-9015-43a0-9d9c-6dcc84f1b76a.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/227736331-8b215419-d26c-40b8-bba4-9439f1d75bd9.png)
](url)

**Comment by Knf69** [comment]
I see that it does not show btcusdt mexc
it only shows a pair of btcusd
The spot shows well

**Comment by Knf69** [comment]
There is also a problem with spot btc/usdt not showing this pair
it only shows btc/busd

**Comment by Knf69** [comment]
@Tucsky still the same problem with spot+perp/futures

[
![image](https://user-images.githubusercontent.com/100996537/227750029-9ac79f49-9d88-411e-993e-5bd400341fac.png)
](url)

**Comment by Tucsky** [comment]
What the problem sir on that screenshot sir @Knf69 I can't tell

I'm able to see all pairs, usdt and not
<img width="824" alt="image" src="https://user-images.githubusercontent.com/5738336/227768177-38db613a-44c8-4121-923d-79d9873046ae.png">

Make sure you have no "quote currency" filters on

**Comment by Knf69** [comment]
> What the problem sir on that screenshot sir @Knf69 I can't tell
> 
> I'm able to see all pairs, usdt and not <img alt="image" width="824" src="https://user-images.githubusercontent.com/5738336/227768177-38db613a-44c8-4121-923d-79d9873046ae.png">
> 
> Make sure you have no "quote currency" filters on

yes it is on the btcusdt/perp list but it doesn't show orders, It only shows btcusd perp
SPOT works only btcbusd, the rest does not show

**Comment by Tucsky** [comment]
Seems like MEXC only have volume on the usdt perps

Here is btcbusd spot, it's working, just very small volume
<img width="186" alt="image" src="https://user-images.githubusercontent.com/5738336/227769175-a9b34133-4f95-4ff0-9acc-1d70bda85f1f.png">

You will have to set the initial threshold to 0 to see anything

**Comment by Knf69** [comment]
> Seems like MEXC only have volume on the usdt perps
> 
> Here is btcbusd spot, it's working, just very small volume

Yes volumen busd shows fine but even $100 btcusdt spot doesn't show the same btcusdc spot of any transaction.

show me one transaction even 1k$ perp btcusdt because I haven't seen any and there is a gigantic volume

**Comment by Knf69** [comment]
@Tucsky it shows badly

[
![image](https://user-images.githubusercontent.com/100996537/228188240-80aa4e85-7020-4f78-bc16-0b9eaa71e661.png)
](url)

**Comment by Tucsky** [comment]
MEXC have no rekt data
what's wrong with the tape here ? looks good to me

**Comment by Knf69** [comment]
> MEXC have no rekt data what's wrong with the tape here ? looks good to me
The point is that it does not show perp / futures Btcusdt and there is 5x more volume than on btcusd, show me 1 perp btcusdt transactions
Even the $1k one

**Comment by Knf69** [comment]
show me 1 btcusdt perp/futures transactions Mexc

**Comment by Knf69** [comment]
> Here you go ![image](https://user-images.githubusercontent.com/5738336/228316458-a7ea15eb-3dda-4970-8a90-6f47067ae611.png)
> 
> Plenty btcusdt trades on the tape What markets are you actually watching haha ![image](https://user-images.githubusercontent.com/5738336/228316788-54a34c67-bc01-488f-a377-c56256e1a9cb.png)
> 
> Full market name for btcusdt perp on Mexc is MEXC:BTC_USDT

I have the same marked but for me it does not show further btc usdt perp

[
![image](https://user-images.githubusercontent.com/100996537/228324430-7d2496ab-03b7-4884-93d9-9c575a673f7d.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/228324467-6ae71947-2551-45a5-9d9f-58abc71cb326.png)
](url)

**Comment by Knf69** [comment]
If you're doing well, throw it on main aggr and see how it works. ")

**Comment by Knf69** [comment]
@Tucsky are you ready to add mexc to the main aggr page?

**Comment by Knf69** [comment]
@Tucsky strange once it works once not aggr I have to refresh after this update.
On one computer it works fine, on the other it doesn't show any transactions

**Comment by Knf69** [comment]
After adding mexc, no transactions are visible. I checked it and my friend has the same problem

**Comment by Tucsky** [comment]
@Knf69 appreciate u letting me know 🙏🏼  I've no idea why you guys can't see... could be because Mexc is blocking you guys IPs ? also if you can export your workspace here it could help.
Still seing them on the main aggr.trade website : 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/5738336/228852211-8b8f2d38-5b8d-4aa9-982e-83c3656e87ff.png">

**Comment by Knf69** [comment]
> @Knf69 appreciate u letting me know 🙏🏼 I've no idea why you guys can't see... could be because Mexc is blocking you guys IPs ? also if you can export your workspace here it could help. Still seing them on the main aggr.trade website : <img alt="image" width="282" src="https://user-images.githubusercontent.com/5738336/228852211-8b8f2d38-5b8d-4aa9-982e-83c3656e87ff.png"> ![image](https://user-images.githubusercontent.com/5738336/228853343-528cc0c1-f9de-425d-8577-8128e35f7123.png)

I check everything :).
give me 1 more day. But everything looks fine so far
