### ISSUE TITLE
Tape not working 

### ISSUE THREAD

**Issue by RealAoki** [Tucsky/aggr#295]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- [ .] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
- [ .] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
- [ .] I documented the issue with screenshots
- [. ] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

The tapes on my presets haven't been working since version 3.2.2 got released, it has also been an issue for some people in my discord. I have tried using multiple browsers including safari, google chrome, and brave and it doesn't seem to be a browser issue. It still doesn't send any alerts through even when it's reset back to its default. 

When I use no preset on incognito the default tape works fine so it seems to be an issue with the preset potentially.

![image](https://user-images.githubusercontent.com/43392886/228775091-f02d819d-9523-4dad-9c34-2f11667eee49.png)

[aggr-shinigamixbt-aggr-btcmaster-ethmaster.txt](https://github.com/Tucsky/aggr/files/11109344/aggr-shinigamixbt-aggr-btcmaster-ethmaster.txt)

![image](https://user-images.githubusercontent.com/43392886/228772549-6d22d103-8526-4fe5-915e-00da2082df50.png)

### Steps to reproduce

(Preferably from a clean environment / incognito mode)
1. TODO
2. TODO
3. TODO
...

**Comment by Tucsky** [comment]
Seems fixed now, sorry about that @RealAoki

**Comment by EmDaz** [comment]
> Seems fixed now, sorry about that @RealAoki

Thank You!

**Comment by RealAoki** [comment]
> Seems fixed now, sorry about that @RealAoki

amazing, thanks for the quick fix!
