### ISSUE TITLE
Script chart (CVD) buggy when using many symbols, maybe due to scattered historical data

### ISSUE THREAD

**Issue by zlex7** [Tucsky/aggr#297]
Thanks for reporting an issue, please review the task list below before submitting the issue :

https://github.com/Tucsky/aggr/issues/186

- [x] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
[localhost-aggr-logs-for-issue.log](https://github.com/Tucsky/aggr/files/11142870/localhost-aggr-logs-for-issue.log)

- [x] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
[aggr-arb_godmode-eth_godmode_dexes-eth_godmode_ethereum-eth-godmode-ethereum (1).txt](https://github.com/Tucsky/aggr/files/11142851/aggr-arb_godmode-eth_godmode_dexes-eth_godmode_ethereum-eth-godmode-ethereum.1.txt)

- [x] I documented the issue with screenshots
- [x] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

https://www.loom.com/share/61c02cab834140f1a1a26c89b1f1d5d2

^ Recording displaying behavior (note e.g COINBASE doesn't show up in first load, but does after reload. Also, UNISWAPARBITRUM shows up only on third reload).

CVD script-based charts display different time series on each load. There's some that will usually show up, e.g binance:SYMBOL, but others will rotate in and out. Also happens when changing time interval of chart and panning backwards in time. My suspicion is there are some holes in certain time series and that's not being accounted for in the chart logic. Supported by certain highly reliable time series (e.g binance websockets) almost always displaying

...

### Steps to reproduce

NOTE: this bug is currently on my own deployed version of aggr-server & aggr, there are some symbols from template file that aren't supported on aggr.trade. However, I've been able to recreate the bug on aggr as well, albeit less often.
 
(Preferably from a clean environment / incognito mode)

1. use this template 
[arb_godmode.txt](https://github.com/Tucsky/aggr/files/11142884/arb_godmode.txt)
2. reload a few times and watch the behavior

**Comment by zlex7** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/13439954/229692560-5d342c1b-b511-42d4-aed0-8374897bd79f.png">

Thought I'd tag another bug here, only showing tenth place in the price chart - is that hardcoded?

**Comment by zlex7** [comment]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/13439954/229692834-1e0c1a23-02dc-469a-a349-f98096aa2181.png">
 
And to add the last (minor) one, there's some stacking at the bottom of the screen when many time series are are all negative. Causes one or two of the labels to not be visible.

Also, each of these screenshots was taken using that custom template on custom aggr deployment, but was able to recreate all 3 on aggr.trade as well!

**Comment by Tucsky** [comment]
> <img alt="image" width="649" src="https://user-images.githubusercontent.com/13439954/229692560-5d342c1b-b511-42d4-aed0-8374897bd79f.png">
> 
> Thought I'd tag another bug here, only showing tenth place in the price chart - is that hardcoded?

Auto by default. (see indicator settings)
It takes the precision from the trades itself so might be a small delay if there isn't a lot of trades 😉

**Comment by Tucsky** [comment]
should be fixed by now on main branch @zlex7

**Comment by zlex7** [comment]
thanks @Tucsky, legend. Out of curiosity, does it have to do with the "fillGapsWithEmpty" attribute on chart, and if no what does that do?

**Comment by zlex7** [comment]
Also, how long does tick size take to adjust with auto? seems like it gets stuck sometimes

**Comment by Tucsky** [comment]
> Also, how long does tick size take to adjust with auto? seems like it gets stuck sometimes

depends on the market activity, a few seconds, if it's stuck there might be an issue :/ send template so I can take a look

> thanks @Tucsky, legend. Out of curiosity, does it have to do with the "fillGapsWithEmpty" attribute on chart, and if no what does that do?

fillGapsWithEmpty allows you to maintain time consistency on a chart that doesn't have a lot of activity, if theres no trades in a candle, it will render the bar anyway (empty bar), this specific feature might be linked to #299
![2023-04-06 09 31 40](https://user-images.githubusercontent.com/5738336/230306453-71c6c052-94a1-4a98-8c99-28a1bb22a6ae.gif)
