### ISSUE TITLE
[Suggestion] Option to lower the volume even more

### ISSUE THREAD

**Issue by test1101111** [Tucsky/aggr#3]
Hey.

I used to run the aggr trade most of the time in the background, but even on the lowest possible setting for the sound parameter(which btw was a bit hard to set it up like that), is still to loud for me, because as I said, it's mostly running in the background and sometimes I am watching some videos or music etc., and the aggr trade sounds are just too loud compared to other things that are playing.
Would it be possible to make it go even lower with the volume then atm?

Thanks.

**Comment by Tucsky** [comment]
When you say lowest possible, is that 0.1?
![image](https://user-images.githubusercontent.com/5738336/121667893-0b231900-caab-11eb-9812-3ae0b24c6df4.png)
Also what thresholds do you use ?

**Comment by Tucsky** [comment]
I still hear the trades at 0.1, but wouldn't say its louder than other things

**Comment by test1101111** [comment]
> I still hear the trades at 0.1, but wouldn't say its louder than other things

Yeah, I meant 0.1, however now I've switched to the amazing v3 and it's somehow much better there. Thanks for the V3!!
Using the occasion, I know it's beta, but some suggestion if it wasn't mentioned already - it would be nice to 1) have a sliders in sound tweaking window as an alternative to text edition 2) option to migrate/copy the settings for colours and sounds etc, from spot to futures window and vice versa.

**Comment by Tucsky** [comment]
> have a sliders in sound tweaking window as an alternative to text edition

Are you talking about the [Pitch](https://en.wikipedia.org/wiki/Pitch_(music)) modulation slider from v2 ?
It is planned. 

> option to migrate/copy the settings for colours and sounds etc, from spot to futures window and vice versa

Ive added the preset feature for audio, in the trades pane setting -> audio threshold -> audio presets
![image](https://user-images.githubusercontent.com/5738336/122283284-ad4c6200-ceec-11eb-9289-366c36ba0d5d.png)

lmk if this is ok for you

**Comment by test1101111** [comment]
> lmk if this is ok for you

Wow that's great and it was quick! Thanks.

> Are you talking about the [Pitch](https://en.wikipedia.org/wiki/Pitch_(music)) modulation slider from v2 ?
Yeah + all other options that could be edited like type of sound, duration, etc.

**Comment by test1101111** [comment]
> > have a sliders in sound tweaking window as an alternative to text edition

A little update. I am not sure if it's due to an v3 update or it was from the beginning like that and I haven't paid enough attention, but I revert back my statement about v3 being ok. Now with the sound and I have the same feeling - even tho I put the audio slider to 0.1, it's still usually similar volume as videos as I watch on youtube etc. and my dream would be aggr.trade to be sth like 5-10% of the volume compare to the video, so that normal trading volume would be almost silent and I would noticed if there is some big movements due to some noises coming from agg.trade tab. I know that there is audio % trigger setting, but it's not a perfect solution.

**Comment by Tucsky** [comment]
0.01 volume I can't hear anything tbh, your audio setup doesn't sounds standard
I always play music while having aggr audio on, I like 0.1

>I would noticed if there is some big movements due to some noises coming from agg.trade tab
other than changing volume
why not change threshold accordingly ?
maybe remove audio script from the two first thresholds or something, then you will only hear 1M+ sounds
Or change audio treshold to 1M or 2M
