### ISSUE TITLE
old.aggr.trade not updating from exchanges

### ISSUE THREAD

**Issue by hoodlum2k** [Tucsky/aggr#302]
Not sure if this is the way, or if it's even supported anymore, but since a couple of days the old aggr.trade can't connect to exchanges: 

https://old.aggr.trade/

Can you, maybe, please fix this? It's light on my phone and been using it for years.

The new version I use on my desktop

Thanks for your awesome work and I hope you consider checking

**Comment by Tucsky** [comment]
I gotchu brother

**Comment by OutOfThisPlanet** [comment]
Same with legacy.aggr.trade

**Comment by Tucsky** [comment]
It's fixed... tho please use the main app. theres no reason to use the old version 😃
if you are going to watch the tape on phone you can use the "lite" trade feed (no gif) which is much faster than legacy/old.aggr.trade and with much more exchanges

**Comment by OutOfThisPlanet** [comment]
I have to be honest, while I think this project is FANTASTIC, I tend to still prefer the old one due to its simplicity. 

The new one has a few settings menus in different areas of the interface, which I find a little bit counterintuitive. 

Thanks for your speedy response, Tucsky :)
