### ISSUE TITLE
Mexc Spot

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#303]
watches mexc spot btc/eth. I have never seen any btc + eth spot transaction

[
![image](https://user-images.githubusercontent.com/100996537/232334036-0c00c15e-571f-4cfe-9a92-611437addde7.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/232334048-8babc93a-d4e5-49c4-8504-8302af138b24.png)
](url)

I set from $1k+ and didn't see any transaction. I think I know where the problem is, the btc/usdt eth/usdt pair was not added

**Comment by Knf69** [comment]
[
![image](https://user-images.githubusercontent.com/100996537/232394382-39f6e70e-defc-4771-99aa-e30cc481ca96.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/232394403-35f39213-3120-466d-aac4-2ebb9240b461.png)
](url)


volumen spot btc+eth is very big on mexc, but must be added btc/usdt+ eth/usdt pair because there is no such in the search engine

**Comment by Tucsky** [comment]
what ticker are you refering to for btc/usdt spot on mexc because I don't see it any "BTCUSDT" on the list here https://api.mexc.com/api/v3/defaultSymbols

there are
MEXC:MBTCUSDT
MEXC:WBTCUSDT
MEXC:LBTCUSDT
but no clue what they are really

**Comment by Tucsky** [comment]
Oh apparently there are two version of spot trading on mexc (v2 and v3) and btcusdt is only on v2 ? 
https://www.mexc.com/open/api/v2/market/ticker
https://api.mexc.com/api/v3/defaultSymbols

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/232478513-4ef3f7a6-0e8e-4b1f-b6bf-41e940faea45.png)
I figured this out
@Knf69

**Comment by Knf69** [comment]
> 

Are you testing this on test net because at my place you can't see further in the search engine for it

[
![image](https://user-images.githubusercontent.com/100996537/232523441-099f15d8-802b-4172-bec1-aebd6f1e3f7d.png)
](url)

**Comment by Tucsky** [comment]
Ah yes because exchange's products are cached for 7 days you have to hit refresh 
![image](https://user-images.githubusercontent.com/5738336/232562510-36dfeef3-c5d6-44e9-a861-21298b24c9f9.png)

**Comment by Knf69** [comment]
> Ah yes because exchange's products are cached for 7 days you have to hit refresh ![image](https://user-images.githubusercontent.com/5738336/232562510-36dfeef3-c5d6-44e9-a861-21298b24c9f9.png)

@Tucsky thanks now all good. LOVE

**Comment by Knf69** [comment]
Mexc spot shows badly now, strange it counts currently.

[
![image](https://user-images.githubusercontent.com/100996537/232681966-f9819985-5fe0-488b-b233-063eebf85d98.png)
](url)

[
![image](https://user-images.githubusercontent.com/100996537/232682008-bc8dcc68-962c-4a57-aee5-a32334ba43b9.png)
](url)

you see 7:42 time-bought someone 7.8btc+4.6 btc=12.4btc.
why aggr shows $1.5mln as it is "50 btc" and not 12.5.
very strangely it is counting as if 4/5x aggr shows more
@Tucsky 

Bug here show

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/232706379-e70bc9c7-3203-4445-8c11-e6d2ac96e6db.png)
Looks good to me @Knf69
 
drop the template here if you want me to look at your settings

**Comment by Knf69** [comment]
> ![image](https://user-images.githubusercontent.com/5738336/232706379-e70bc9c7-3203-4445-8c11-e6d2ac96e6db.png) Looks good to me @Knf69
> 
> drop the template here if you want me to look at your settings

I'll check it quietly at my place today and let you know
