### ISSUE TITLE
Can you add old data?

### ISSUE THREAD

**Issue by sametguvendi** [Tucsky/aggr#306]
Hi can you add old datas like https://whalehuntapp.com/ it will be much more useful if you can achive this :)

**Comment by Knf69** [comment]
@sametguvendi What is it about,what do you want added?

**Comment by adeacetis** [comment]
@sametguvendi Please provide context and specifics about this enhancement.
Why would you need this data ?
How can we access historical data? Do they have a Websocket API?

**Comment by adeacetis** [comment]
Hi @sametguvendi,

Thank you for posting your request.

It seems you are asking if we're going to integrate Whale Hunt App signal service with aggr.

Unfortunately, we don't have access to the feed of data as it is only available to subscribers. 

If Whale Hunt App wants to provide an integration proposal (https://whalehuntapp.com/), they are free to contact @Tucsky and provide a Pull Request proposal offering the integration.

On our end, it's unlikely we'll do anything presently.
