### ISSUE TITLE
[DATA] Add SUI to historical data

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#307]
Pleaseeeee <3

**Comment by adeacetis** [comment]
@Tucsky added partial support for historical data:

For now, we only have perps, no spots:
- BYBIT - SUIUSDT,
- KUCOIN - SUIUSDTM
- MEXC - SUI_USDT
- OKEX - SUI-USDT-SWAP

@lmvdz double-check if this is alright with you.

**Comment by lmvdz** [comment]
Thank you very much!
