### ISSUE TITLE
Certificate Out of Date

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#309]
![image](https://github.com/Tucsky/aggr/assets/2179775/9dcd90a7-5b8a-4ce4-94eb-21b32152e610)

**Comment by adeacetis** [comment]
Hey @lmvdz,
No problem on my end.

Will leave this issue open for a few days, if nobody experiences the same issue. I will close it.

Have a good day.

**Comment by lmvdz** [comment]
Nah it's working on my end as well! I think it was just down for a few minutes. @adeacetis

**Comment by adeacetis** [comment]
Closing, thanks.

**Comment by Tucsky** [comment]
Thanks for the heads up!
