### ISSUE TITLE
[BUG] `Go Fulscreen` in the Menu component renders on two lines.

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#310]
Thanks for reporting an issue, please review the task list below before submitting the issue :

- [X] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
❌ There are no errors.
- [X] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
❌ Not required here, the issue occurs with any template.
- [X] I documented the issue with screenshots
- [X] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

This issue has been discovered while testing #289.

We noticed that `Go Fulscreen` in the Menu component renders on two lines.

![image](https://github.com/Tucsky/aggr/assets/20586054/b4fe07e4-914e-4944-add3-f35643a090f5)

It is expected that the label renders only on one line.

...

### Steps to reproduce

1. Go to the live site at https://aggr.trade/
2. Open the menu at the bottom right of the page.
3. Click the "Go Fullscreen" button.
4. Press the ESC key to leave fullscreen mode
5. Open the menu at the bottom right again. If the bug doesn't show up, repeat steps 3-5 until it does.

**Comment by adeacetis** [comment]
Also shows on mobile:
![Screenshot_2023-05-11-02-06-22-782_com.mi.globalbrowser.jpg](https://github.com/Tucsky/aggr/assets/20586054/5379227b-28ce-4143-9d9e-9b4f0eafe02d)

**Comment by adeacetis** [comment]
@Tucsky you closed the issue but it's not fixed.

Did you deploy already?

What's your deployment strategy?

**Comment by Tucsky** [comment]
It is fixed on the repo @adeacetis 
All deploiements are manual !
But I try to keep tucsky.github.io/aggr in sync at all time
