### ISSUE TITLE
[DATA] Add Crypto.com to AGGR

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#325]
**Exchange's name:** Crypto.com
**Exchange's URL:** https://crypto.com/

**Type:** SPOT | PERP | FUTURES

**Public WebSocket API documentation URL (WebSocket):** https://exchange-docs.crypto.com/exchange/v1/rest-ws/index.html#introduction

**Comments:**

**Comment by Knf69** [comment]
This is a very good decision! gl work

**Comment by adeacetis** [comment]
Live from 3.3.x

See commits:
https://github.com/Tucsky/aggr/commit/6aa6fdc257941733e80de6266eb0565f16836139
https://github.com/Tucsky/aggr/commit/51ec754ff26fba2efea856b52f6a48b864466848
