### ISSUE TITLE
Sound new bad brrrr

### ISSUE THREAD

**Issue by Ichimikichiki** [Tucsky/aggr#326]
So the latest version has killed the old cached copy I had running on phone in Chrome. And the sound as of a few years ago, are just horrid. There is no depth to them. What version do I have to go back to in order to host with the old sounds? And yes I know about the pitch. It's not the pitch. It's the actual sound. And yes I use Chrome as recommended for optimal sound.

**Comment by Tucsky** [comment]
I know what you mean about the depth thing, it should be there
The good news is that default sounds have NOT changed in years
so to me is a template issue, please send me your template so I can take a look

**Comment by Ichimikichiki** [comment]
Yes I'm fully aware. As mentioned, it changed to some terrible sound like 3 maybe 4 years ago. I've been using a saved cached version of the site from back then. The previous version that was running before it went to aggr.trade was the best.
Here's a screenshot I found. All this was before the pitch feature was added.
![Screenshot_20210314-053621](https://github.com/Tucsky/aggr/assets/40658431/f7438387-f890-44d8-82e8-28e3b370eb5e)

**Comment by Ichimikichiki** [comment]
I'm looking.

Might be easier just to checkout an earlier commit and see if that works. But I remember mentioning it to you at the time in discord. It was overvolume on the app settings itself, so it just distorted really nicely and had the phattest sound.

**Comment by Tucsky** [comment]
ok let's try something @Ichimikichiki 

go on https://tucsky.github.io/aggr
in the trades pane settings : 
- 1st & 2nd threshold set to 100k (like old aggr)
- select "legacy 🎵" preset
![legacy](https://github.com/Tucsky/aggr/assets/5738336/6268fa2f-7d4c-4ffe-9c5e-77d5e0965d0a)


Or just drag n drop this text file into the app : 
[legacy-trades-pane.txt](https://github.com/Tucsky/aggr/files/11691225/legacy-trades-pane.txt)

**Comment by Tucsky** [comment]
or just could just go on https://legacy.aggr.trade/

**Comment by adeacetis** [comment]
Closing this issue as it is stalling.
