### ISSUE TITLE
Crypto.Com

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#329]
Crypto.Com
https://crypto.com/eea

Spot/Perp/Futures

I think it is a large stock exchange real volumen when it is really worth adding. I've been sitting there for 2 years and I've never had any problems

**Comment by Knf69** [comment]
with today transfer so that this is not a fake stock exchange and there are serious people sitting there.

https://twitter.com/whale_alert/status/1666642506186932224

**Comment by adeacetis** [comment]
Duplicate of #325
