### ISSUE TITLE
Historical data of some pairs have been removed I guess, will that be available again?

### ISSUE THREAD

**Issue by olraleads** [Tucsky/aggr#334]
[/Thanks]) for reporting an issue, please review the task list below before submitting the issue :

- [ ] I added my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output in the issue (open the console first, try to reproduce the issue then see if there is anything)
- [ ] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
- [ ] I documented the issue with screenshots
- [ ] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue
Historical data of some important pairs like mask,rndr,inj,jasmy and more pairs historically data has been removed. I have been using those alts data for months but suddenly those are vanished. Please can you guys solve it and get them back?
...
![image](https://github.com/Tucsky/aggr/assets/136142949/6943bb3c-deef-46c0-b63f-b9bd252fe568)

### Steps to reproduce

(Preferably from a clean environment / incognito mode)
1. TODO
2. TODO
3. TODO
...

**Comment by Tucsky** [comment]
Server went in infinite crash loop, back now :)
