### ISSUE TITLE
[DATA] Add <TUSD (TrueUSD) Pairs> to AGGR

### ISSUE THREAD

**Issue by Casidea** [Tucsky/aggr#345]
Is it possible to add "TUSD" pairs (TrueUSD) to Aggr ?

TrueUSD seems to have had a huge influence to the recent pump from 24800 to 30000+ according to the people at Crypto Quant.

I added the BTC/TUSD pair from Binance to a Trading View Aggregated CVD script and it did somewhat change the trajectory.
And that's just Binance.
So I thought adding at least a BTC/TUSD pair from major exchanges would be helpful for improving CVD accuracy.

Apologies in advance if my comments aren't helpful in adding such feature. (very new github and coding)
And thx in advance.

**Comment by adeacetis** [comment]
I guess your demand is to add historical data for BTC/TUSD. A quick search on Coinmarket shows that the pair you are mentioning is actually first in terms of volume.

![image](https://github.com/Tucsky/aggr/assets/20586054/3f9de54a-6909-485f-b82b-4af914c2d75f)

So yes, I would add this one as well. This is in @Tucsky's hands now.

Thank you for the heads up.

**Comment by Casidea** [comment]
> I guess your demand is to add historical data for BTC/TUSD. A quick search on Coinmarket shows that the pair you are mentioning is actually first in terms of volume.
> 
> ![image](https://user-images.githubusercontent.com/20586054/251214057-3f9de54a-6909-485f-b82b-4af914c2d75f.png)
> 
> So yes, I would add this one as well. This is in @Tucsky's hands now.
> 
> Thank you for the heads up.

Yes and thank you.

And my apologies if it sounded like a "demand". I meant it as a "humble request". 
I really appreciate all efforts made towards this huge project.

Thanks again!

**Comment by adeacetis** [comment]
No worries. Thank you for the heads up. ;) I don't have access to the server, so I can just pass the ball.

**Comment by adeacetis** [comment]
@Tucsky Can we add this pair to the available ones in prod?

**Comment by Tucsky** [comment]
> @Tucsky Can we add this pair to the available ones in prod?

sure thing 👍🏼 
planning to add the following markets : 
BINANCE:btctusd,BINANCE:ethtusd,BINANCE:bnbtusd,BINANCE:xrptusd,BINANCE:adatusd,BINANCE:ltctusd,BINANCE:bchtusd,BINANCE:arbtusd,BINANCE:idtusd,BINANCE:ldotusd,BINANCE:matictusd,BINANCE:optusd,BINANCE:soltusd,BINANCE:ssvtusd,BINANCE:rdnttusd,BINANCE:dogetusd,BINANCE:edutusd,BINANCE:suitusd,BINANCE:pepetusd,BINANCE:flokitusd,BINANCE:mavtusd,BINANCE:cfxtusd,BINANCE:pendletusd,BINANCE:xvgtusd,BINANCE:arkmtusd,BINANCE:avaxtusd,BINANCE:comptusd,BINANCE:quicktusd,KUCOIN:XRP-TUSD,KUCOIN:BTC-TUSD,KUCOIN:ETH-TUSD

let me know if you see one that I missed

**Comment by Casidea** [comment]
> > @Tucsky Can we add this pair to the available ones in prod?
> 
> sure thing 👍🏼 planning to add the following markets : BINANCE:btctusd,BINANCE:ethtusd,BINANCE:bnbtusd,BINANCE:xrptusd,BINANCE:adatusd,BINANCE:ltctusd,BINANCE:bchtusd,BINANCE:arbtusd,BINANCE:idtusd,BINANCE:ldotusd,BINANCE:matictusd,BINANCE:optusd,BINANCE:soltusd,BINANCE:ssvtusd,BINANCE:rdnttusd,BINANCE:dogetusd,BINANCE:edutusd,BINANCE:suitusd,BINANCE:pepetusd,BINANCE:flokitusd,BINANCE:mavtusd,BINANCE:cfxtusd,BINANCE:pendletusd,BINANCE:xvgtusd,BINANCE:arkmtusd,BINANCE:avaxtusd,BINANCE:comptusd,BINANCE:quicktusd,KUCOIN:XRP-TUSD,KUCOIN:BTC-TUSD,KUCOIN:ETH-TUSD
> 
> let me know if you see one that I missed

Since I haven't seen TUSD being added yet, I though if it isn't a huge hassle of adding another pair, I would appreciate it.
Reason is the following.

Binance very recently added another pair BTC/FDUSD and ETH/FDUSD. (August 4th)
https://www.binance.com/en/support/announcement/binance-adds-btc-fdusd-eth-fdusd-trading-pairs-and-updates-the-zero-fee-bitcoin-trading-program-0e4155610e6f4e8bbaaa332545dc43a2

While currently there is still not much volume yet, they're offering free trading fees just like they did with TUSD.
Just pure assumption, but I personally feel that there is a possibility of Binance (or whoever is behind it) using FDUSD just like they did with TUSD to pump the price up.
(Again, this is just pure speculation and NFA.)

I just thought that if its not a huge trouble of adding the FDUSD pair while you're adding the TUSD pairs, it would be greatly appreciated.

Or maybe I should just wait till it gets volume and then make another thread (I'm not sure).
If you have to go through a lot of work to add said pair, please ignore this request of course.

Thanks in advance :)

**Comment by adeacetis** [comment]
TUSD pairs are available in staging, but no historical data offered so far.

![image](https://github.com/Tucsky/aggr/assets/20586054/4feb6528-c570-457c-a8c5-18aa1a0c6328)
