### ISSUE TITLE
Any plans for an orderbook visualization?

### ISSUE THREAD

**Issue by codestoned1** [Tucsky/aggr#346]
Something like the trade tape for but for book updates. This would require quite a bit of exchange-specific implementation so maybe could just be done for binance & binance futures?

**Comment by adeacetis** [comment]
Hey,

Not that I know of. However, there's something similar you might want to try out in Aggr Discord Server. 

https://discord.com/channels/1110160121813803058/1110160644793184316/1114823233561178142

**Comment by adeacetis** [comment]
There's no plan currently for OB visualization. Closing this request.
