### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disabled') ― when trying to use custom template

### ISSUE THREAD

**Issue by viralhysteria** [Tucsky/aggr#348]
I've been using aggr with a template I made last summer and I noticed today that all of a sudden no data is being served for any template I use except default.  If I manually toggle each individual element, they reappear until the next reload, but they don't actually update value-wise. I'm not seeing anything in the commit log that can reasonably explain this change in behavior.

![aggr1](https://github.com/Tucsky/aggr/assets/1983431/a160d922-4d38-4395-83cc-22d9a9c3dafa)

***How the template should/used to look***
![aggr2](https://github.com/Tucsky/aggr/assets/1983431/ece0bd84-642b-4058-8245-1957a56f7c70)

***How the template currently looks***
![aggr3](https://github.com/Tucsky/aggr/assets/1983431/ce259038-fa5b-4d88-8c13-766144dfe601)

This issue is replicated across any and all of the other saved templates I have as well.

I've linked the source code for the template externally because it's far beyond the character limit
[bin.disroot/?2c8a4c536122f0cd#4dGExX76atLqn94mt9ZLxyv1YjCK54iB81dYQQ3EN3Ra](https://bin.disroot.org/?2c8a4c536122f0cd#4dGExX76atLqn94mt9ZLxyv1YjCK54iB81dYQQ3EN3Ra)

**Comment by Tucsky** [comment]
This could be linked to deleted exchanges, and template still referencing them
I'm attempting a fix, is it loading ok if you hard refresh now?

**Comment by viralhysteria** [comment]
yes, whatever you did worked and everything is functioning as expected now. thanks so much for the quick fix.

**Comment by Tucsky** [comment]
> i've been a bit lazy about removing the old exchanges.

You shouldn't have to bother about this, it's my mistake
Thanks for letting us know !
