### ISSUE TITLE
[BUG] Time string show single digit minutes in Trade feed

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#349]
NA

NA

- [x] I documented the issue with screenshots
![image](https://github.com/Tucsky/aggr/assets/20586054/0680f9ad-588b-4810-a8dc-cf394b5a2b89)

- [x] I provided a clear and concise description of what the bug is (see both sections below)
When the time of trade hasn't reached the first 10 minute in an hour, it shows a single digit instead of two.

**Comment by levi-bravenboer** [comment]
Hi i would like to help fix this bug. Could you assign it to me?

**Comment by adeacetis** [comment]
> Hi i would like to help fix this bug. Could you assign it to me?

Hey,

Are you in the Discord?

Cheers
