### ISSUE TITLE
[DATA] Zoomex Exchanges

### ISSUE THREAD

**Issue by Knf69** [Tucsky/aggr#351]
**Exchange's name:** Zoomex
**Exchange's url:** (https://www.zoomex.com/en-US/)

**Type: | PERP 

**Public WebSocket API documentation url (WebSocket):** <Insert webpage url>

Me and my colleagues are testing this exchange looks great zero lag perfect real volume
what do you think about her. Last month was very good on this exchange, zero problems  zero lags when large volumes

**Comment by adeacetis** [comment]
I have contacted support and they said they don't have public API available.

We can't implement this exchange today, perhaps in the future.
