### ISSUE TITLE
[DATA] Add CoinEx to AGGR

### ISSUE THREAD

**Issue by vkachan** [Tucsky/aggr#353]
**Exchange's name:** CoinEx
**Exchange's url:** [<Name of exchange>](https://www.coinex.com/)

**Type:** SPOT | PERP

**Public WebSocket API documentation url (WebSocket):** https://viabtc.github.io/coinex_api_en_doc/futures/#docsfutures002_websocket001_general

**Comments:** Good and reliable exchange, would be great to add it into aggr as well.

**Comment by adeacetis** [comment]
Duplicate #331
