### ISSUE TITLE
[BUG] Text overlaps time in the trade feed

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#359]
# Environment:

aggr.trade - production

# Steps to reproduce the issue:
 
1. Setup a default panel
2. Reduce the width of the panel until the elapsed time disappears
![image](https://github.com/Tucsky/aggr/assets/20586054/daf28c3d-9f61-4dfa-809d-5988a2fcbda9)

3. Open the panel settings and change the time format to `HH:MM`

![image](https://github.com/Tucsky/aggr/assets/20586054/99c8118f-551f-45f0-b2c5-dbd313fd628b)

4. Watch the values that are being displayed, the contract's value, and the underlying size that appears when you hover one line now overlap the time.

![image](https://github.com/Tucsky/aggr/assets/20586054/45735d43-2c06-424e-b9a7-8a53dee8e009)

Noting that the ellipsis 

# Proposed solutions:

I could imagine a mix of those solutions:
* Set fluid font-size depending on pane width
* Set a min-width for this panel type. Under that value, the panel loses its value anyway. Thinking out loud, the ideal min-width would probably be equal to the smaller current popular mobile viewport width.
* Hide the canonical time first before limiting the user's action.

**Comment by Tucsky** [comment]
easy fix : untick price column in settings ("show prices" OFF)

**Comment by adeacetis** [comment]
What if someone wants to see the price...
