### ISSUE TITLE
I can't access the site

### ISSUE THREAD

**Issue by MaximMakarskiy** [Tucsky/aggr#361]
Hello. When I tried to access the site, I received a message...

" A mutation operation was attempted on a database that did not allow mutations.

Either reset the browser data on this site or contact the devs on the github :
https://github.com/Tucsky/aggr/issues/new "

**Comment by adeacetis** [comment]
We had an issue with SSL certificate, it seems resolved now, could you check if that is working properly now ?

**Comment by MaximMakarskiy** [comment]
the site is working now, thank you
