### ISSUE TITLE
SSL Certificate Issue [NET::ERR_CERT_DATE_INVALID]

### ISSUE THREAD

**Issue by skarborous** [Tucsky/aggr#362]
Getting NET::ERR_CERT_DATE_INVALID when loading website (Firefox and Chrome, different PCs)

Developer Console shows (VM42:5 crbug/1173575, non-JS module files deprecated.)

"Your connection is not private
Attackers might be trying to steal your information from charts.aggr.trade (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)

NET::ERR_CERT_DATE_INVALID

charts.aggr.trade normally uses encryption to protect your information. When Chrome tried to connect to charts.aggr.trade this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be charts.aggr.trade, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

You cannot visit charts.aggr.trade right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later."

**Comment by adeacetis** [comment]
We're back.
