### ISSUE TITLE
[DATA] Binance is phasing out BUSD in favors of FDUSD

### ISSUE THREAD

**Issue by adeacetis** [Tucsky/aggr#371]
**Is your feature request related to a problem? Please describe.**
Binance seems to be moving trading volumes out of BUSD. The pairs are still listed but the volume is in FDUSD, at least for majors.

**Describe the solution you'd like**
We need to add the new stablecoin as a filter option in the SearchConnection dialog but also start to replace BUSD's historical with FDUSD's.

I know we don't have processes on how to deal with phasing out stablecoins and what to do with the data, especially long-term data. I don't think we need to get rid of it.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Casidea** [comment]
https://github.com/Tucsky/aggr/issues/345#issuecomment-1666591661

I stated back in August in the above post that Binance might pump the market with FDUSD just like they did with TUSD.
And I think its happened/happening. (compared the CVD between pairs)

Now, the BTC/FUSD pair has the most volume according to coinmarket cap.
I hope this pair eventually gets added as well.


![btc volume](https://github.com/Tucsky/aggr/assets/138615050/18d31ced-7b2e-4bd7-bef6-2b9443a672dc)

**Comment by adeacetis** [comment]
You are right and it's part of #381 We're still prepping it.

**Comment by Casidea** [comment]
Thank you very much!

**Comment by adeacetis** [comment]
Added on staging, ready for release with 3.5.0 
![image](https://github.com/Tucsky/aggr/assets/20586054/e69e7c64-b7f6-4196-bbd9-348292df86c8)
