### ISSUE TITLE
[Feature] Auto fit scale function: exclude drawings of indicators

### ISSUE THREAD

**Issue by petrichor-vibes** [Tucsky/aggr#379]
Some main chart indicators with auto-scaling, making the price heavily compressed on the Y-axis.

Provide an option similar to the "scale price chart only" option in tradingview.

plz

**Comment by Tucsky** [comment]
> Provide an option similar to the "scale price chart only" option in tradingview.

So there's no slick method for this at the moment, but if you're [on the staging environment (3.4.1+)](https://tucsky.github.io/aggr), you can totally overlay while snapping on the main indicator's top/bottom edges. 

Every indicator comes with just 1 tweakable price scale in the UI (I'm talking top/bottom edges, vol/price scale, and log/linear). But if you wanna overlay a series from the same indicator over the main one, just toss a random priceScaleId 
(remember only right and left will actually be visible as scale on the chart)

`line(firstSerieValue) // This one's gonna use the indicator priceScale `

```
line(firstSerieValue) 
line(secondSerieValue, priceScaleId=randompriceScaleID1) // 2nd over first
line(secondSerieValue, priceScaleId=randompriceScaleID2) // 3rd over first
line(secondSerieValue, priceScaleId=randompriceScaleID3) //
```

If things go a bit wonky and the scales fall outta sync, just hit hide and then show on the indi controls in the chart. Easy fix! 😃

**Comment by petrichor-vibes** [comment]
Thanks for the reply, the excellent work you do is much appreciated! @Tucsky
