### ISSUE TITLE
Support for Bybit V5 Websocket API

### ISSUE THREAD

**Issue by skeppern** [Tucsky/aggr#383]
Bybit is phasing out the old V2 api's that the code is currently using.

So i wish to request a feature request that replaces the old V2 websocket listeners to the new V5. The app has recently started complaining about connecting to the old endpoints because Bybit is closing them down, if not already done so.

The new endpoints is as follows:
Spot: wss://stream.bybit.com/v5/public/spot
USDT, USDC perpetual & USDC Futures: wss://stream.bybit.com/v5/public/linear
Inverse contract: wss://stream.bybit.com/v5/public/inverse

The docs: https://bybit-exchange.github.io/docs/v5/ws/connect

Thanks.

**Comment by adeacetis** [comment]
We're currently preparing to release 3.5.0 which includes this improvement for the frontend and the backend.

Some outstanding issues and instabilities did force us to push the release. Trying to move ahead early next week.

Thank you for the heads up.

**Comment by skeppern** [comment]
Thanks! I have had to turn off the bybit streams in the app since it is constantly retrying. Keep up the good work guys, I love this app and use it frequently!

Leaving this image here as a reference to why I placed the request above.

![image](https://github.com/Tucsky/aggr/assets/6838209/d3798557-2571-4fab-bdb1-cfc9bcbcb920)

**Comment by Tucsky** [comment]
Hot fixed just now on aggr.trade
I appreciate the warning @skeppern 🙏🏼
