### ISSUE TITLE
[Suggestion] Keep the old layout and have a toggle

### ISSUE THREAD

**Issue by sezonis** [Tucsky/aggr#4]
I'm going to be straight with you. V3 is a disaster waiting to happen. 

The graph is just confusing and text too small. I used to visit this site on the get go (from anywhere) without having to do any setup. Go on site, pick time frame and that's it. With the introduction to v3, it just doesn't seem to feel as smooth and look as great. Looks more cluttered and is too tiny and confusing for the naked eye. Too much color difference and too many different trades being tracked. In my opinion, it is a downgrade compared to the older version. Having just the one panel tracking everything in real time was pretty much perfect. You got all the trades in near real time and that's really all there is to it. 

I know many people have their own opinions. All I ask is for you to give people options. For whatever reason, every company is making their nice UI's look like shit lately and (not trying to be rude here) but you seem to be following in their footsteps. 

I know what I'm saying may be controversial, as there may be others that like the new layout. It's just too much of an eye soar in my opinion

**Comment by crypto-7oM** [comment]
this would be great

**Comment by joaoesp** [comment]
I agree, keep it simple

**Comment by OrangeChannel** [comment]
I'm going to counter this by saying the customization and options in the new layout are amazing. The older version's default screen was more simple than this so I agree there should be an option to switch back to v2. However, I've been wanting more panes and a better charting interface for ages and this update is looking great so far. :+1:

**Comment by sezonis** [comment]
> I'm going to counter this by saying the customization and options in the new layout are amazing. The older version's default screen was more simple than this so I agree there should be an option to switch back to v2. However, I've been wanting more panes and a better charting interface for ages and this update is looking great so far. 👍

I agree. Some people will like it, some will hate it. But as long as there's an option to use the old, then it's all good. 

I know how much effort must have been put to create it. I wasn't trying to be mean or anything to the dev, I just got a little bit anxious and angry because of all these new UI changes that have been happening lately to other sites. 

I'm sure v3 will be fleshed out in the future as well, to make it balanced for everyone.

**Comment by Tucsky** [comment]
So about the colors, I'm actually color blind and so you guys probably see things wayyy too saturated, but is ok for me
PR / suggestion are open (i mean it) to see if we can improve the default colors, you can also share the good template so we can have a vote :) 

Change is scary for many, which makes change hard. 
Just sit tight, v3 is still fairly beta stage & takes time to stabilizing this thing as more feature brings more complexity 
Also this is no "Company" just a free time dev thingy...

**Comment by Tucsky** [comment]
> I used to visit this site on the get go (from anywhere) without having to do any setup

Yes this is a real topic as the overall site is too desktop oriented rn.
The panes stay the same regardless of browser window, which is not too disturbing for desktop ppl but hybrid users might find this  annoying af
I'm not sure of the correct expected behavior for this ?

on v2 I use to have it running on relatively small width window, full height or just landscape "popup", if window too small it just displayed everything in a column so that was easy

v3 its always full screen, more charts, more feeds etc, no space wasted

**Comment by sezonis** [comment]
> So about the colors, I'm actually color blind and so you guys probably see things wayyy too saturated, but is ok for me
That makes sense. I mean it wouldn't be a big deal if there was a toggle on the top of the menu (visible without having to click on sub menus) that changes colors. Could call it "new/legacy". 

> PR / suggestion are open (i mean it) to see if we can improve the default colors, you can also share the good template so we can have a vote :)
> 
> Change is scary for many, which makes change hard.
> Just sit tight, v3 is still fairly beta stage & takes time to stabilizing this thing as more feature brings more complexity
Thanks for this. I appreciate that you are here to listen to your community. I know it can be tough getting that sweet spot that everyone can accept. 

> Also this is no "Company" just a free time dev thingy...
I  just meant that you were following the footsteps of companies. I didn't necessarily mean you were a company.



> > I used to visit this site on the get go (from anywhere) without having to do any setup
> 
> Yes this is a real topic as the overall site is too desktop oriented rn.
> The panes stay the same regardless of browser window, which is not too disturbing for desktop ppl but hybrid users might find this annoying af
> I'm not sure of the correct expected behavior for this ?
I'm not really good with design unfortunately. I know it's probably difficult to maintain mobile/desktop behavior. I wish I could help you. With V3 on mobile it is also slower than the desktop. Took around 12seconds to populate v3 while v2 took like 2 seconds. Hopefully some others may be able to help you out here. 
 
> on v2 I use to have it running on relatively small width window, full height or just landscape "popup", if window too small it just displayed everything in a column so that was easy
> 
> v3 its always full screen, more charts, more feeds etc, no space wasted
I see. Yea, the versions are quite different between the two.

**Comment by OneArb** [comment]
Ain't broken, don't fix it! 

I cannot think of a way to make version 2 any better. Just works! One in a million!

When reducing v2 chart to a tiny portion of the screen, trades auto-fit under the chart.

Can that behavior carry over to v3? Perhaps some sort of auto-fit for those who want to plug and play?
I find dragging then resizing tedious. Auto-fit.

Is a choice of 4-5 color schemes including legacy color out of question?
