### ISSUE TITLE
[BUG] Trades not showing up when i use this layout all of a sudden.

### ISSUE THREAD

**Issue by rakeshthestraight** [Tucsky/aggr#400]
# Bug report

> ❤️ Thanks for reporting an issue. Please review the task list below before submitting and delete any sections you deem irrelevant.

## Checklist

- [x] I provided a clear and concise description of the bug (see both sections below).
- [x] I documented the issue with screenshots.
- [x] I have attached an [export of my Aggr database](https://imgur.com/a/traIrKb) to the issue.
- [x] I checked my [browser's console](https://balsamiq.com/support/faqs/browserconsole/) output for errors and included it in the issue if any.

## Description of what the bug is

Trade feed not loading on coinbase. Also, When I click on sources, Its not loading any of the pairs properly. Issue started today.

- **Environment:** (e.g., aggr.trade desktop)

Aggr.trade, Firefox browser/ Chrome browser. Desktop.

- **App version:**

v 3.5.6

Steps to reproduce:

[aggrsetup_aggrsetup.json](https://github.com/user-attachments/files/16705640/aggrsetup_aggrsetup.json)

## Screenshots

![aggrss](https://github.com/user-attachments/assets/7cff50d3-77f5-45ae-b2a4-3edd4e8a068e)

## Export Aggr Database

[aggr-aggrsetup-h20k.json](https://github.com/user-attachments/files/16705655/aggr-aggrsetup-h20k.json)

## Browser's console logs
*Copy and paste the output of errors.* 
 
```
console.error(
              `Experiment ${id} has unknown featureId: ${featureId}`
            );
```

```
Experiment add-an-image-to-pdf-with-alt-text-rollout has unknown featureId: addAnImageInPDF RemoteSettingsExperimentLoader.sys.mjs:709:21
    _validateBranches resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs:709
    checkRecipe resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs:616
```

**Comment by rakeshthestraight** [comment]
![aggr2](https://github.com/user-attachments/assets/6223ed73-5bad-4cf2-996a-96535961a5b7)
Only 2 pairs showing up in sources.

**Comment by rakeshthestraight** [comment]
also i just noticed coinbase orderflow wont load for me many more sites like - oktoki.com and coinlobster.com as well. maybe they banned my ip or something lol. wtf

**Comment by Tucsky** [comment]
Coinbase deprecated the endpoint we were using yesterday, i updated it now 👍🏼 
Thanks for the alert !!

**Comment by rakeshthestraight** [comment]
Thanks Tucsky , Your work is amazing!
