### ISSUE TITLE
About sentiment

### ISSUE THREAD

**Issue by mrjamesbruno** [Tucsky/aggr#404]
Hello, 
I just want to know where the data for sentimenttv and sentimentmex come from and how it is aggregated. What is the formula for this data. I couldn't find the answer in the code and didn't know where to ask, so I'm writing here.

Thanks
Yura

**Comment by adeacetis** [comment]
This is a proprietary algorithm that analyze sentiment in different chat rooms / trollbox. It was discussed in the Discord server. You are welcome to join us. See pinned issue here on Github.
