### ISSUE TITLE
SignificantTrades (old) vs aggr (new) settings storage

### ISSUE THREAD

**Issue by yerb** [Tucsky/aggr#42]
First of all, the work you have done on v3.aggr is amazing!

A couple of questions about storage.

- Will you keep the old version as something like `old.aggr.trade` ? The neat feature was the ability to keep multiple instances of local storage by using `<prefix>.aggr.trade` so I'm guessing the new URL prefix could be `<prefix>.old.aggr.trade` 
- Where is the v3 settings storage? Under settings I see Download workspace option, but how do I restore workspace from that downloaded file on my local instance or in another browser?
- When I was running my local instance of SignificantTrades I could simply copy local storage settings and duplicate them on another url using [LocalStorage Manager chrome extension](https://chrome.google.com/webstore/detail/localstorage-manager/fkhoimdhngkiicbjobkinobjkoefhkap) but v3 doesn't seem to be using local storage to keep settings, how does that work?

**Comment by lmvdz** [comment]
As far as the prefix part check issue #9 

You can drag and drop the json into the settings pane to import the workspace. In my #40 I added another workspace option to import workspace via an <input type"file">

**Comment by Tucsky** [comment]
v2 used localStorage indeed, v3 use indexedDB

now both method are NOT shared between subdomain. Making it seems like it's a feature on v2, but its just a security measure.

It created a lot of duplicated data on the v2 (for exemple all exchanges products duplicated for each subdomains)
Now v3 handle workspace by itself 
it allows data sharing between workspace (common presets for colors, thresholds, audio), common indicators and of course exchanges products.

So idk about using subdomains on v3, maybe as a shortcut to create a new workspace with ID beeing what's before *any letters*.aggr.trade, and automatically add the matching markets (see https://github.com/Tucsky/aggr/issues/9#issuecomment-860270637), once v2 replace v3 on the main domain


> Will you keep the old version as something like old.aggr.trade

yes
