### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Gitinghubed** [Tucsky/aggr#43]
Dear im not experienced in computer lingo.
Hope to make a small video describing how to run steps i would be thankful

**Comment by Gitinghubed** [comment]
I also notcied in the new Version its not easy for iphons to use

**Comment by Tucsky** [comment]
Works quite well on my 5y old mobile device
![Screenshot_20210626-194833](https://user-images.githubusercontent.com/5738336/123521534-91e51200-d6b7-11eb-9c8f-7c9843f57a71.jpg)
