### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by lmvdz** [Tucsky/aggr#48]
First off I noticed using the zoom in/out on the chart pane doesn't actually do anything.

Secondly the zoom mapping gets offset when removing/adding panes.

Steps to reproduce.

-----

Incognito: https://v3.aggr.trade/
Remove the chart pane
Add a new chart pane
Zoom In/Out using the Chart pane --- zooms in/out the rekts pane
Zoom In/Out using the Rekts pane --- zooms in/out the trades pane
Zoom In/Out using the Trades pane --- doesn't do anything

-----

My thoughts are that the mapping order of which pane is assigned to which zoom in/out gets messed up somewhere along the way when adding/removing panes.

![](https://i.gyazo.com/34d402dc13b0003b6a0831e17540bb8f.gif)

**Comment by Tucsky** [comment]
Haha yeah this is annoying, I should querySelector using id of pane instead of index

**Comment by Tucsky** [comment]
![2021-06-30 22 27 30](https://user-images.githubusercontent.com/5738336/124026875-86188900-d9f2-11eb-8573-a96b6217cf64.gif)
closing for now
