### ISSUE TITLE
Sound is delayed on the new version

### ISSUE THREAD

**Issue by crypto-7oM** [Tucsky/aggr#5]
So, I've been using this site for YEARS and it has been instrumental in my success as a trader (thank you).  The new version, while I do not like it at first, I'm sure I'll get used to it, but I've noticed right off the bat that the sound is delayed 1-2 seconds.  I have old AND new versions open at the same time and the new version is CLEARLY behind on everything.

Hopefully this can be fixed?  Are we able to run the previous version locally permanently if need-be?

**Comment by Tucsky** [comment]
The delay.. Not quite a bug, more a feature
Absolutely no one or your speaker wants to hear a dozen Millis on the buy playing at the same time, thus the delay 
And BTC had yet to make a move like today so wasn't so much of a problem at the time :)
Anyway I deployd a fix basicaly it decrease the delay when a lot of trade are coming
80ms when it's chill
40ms when 10 to 20 are currently playing or queued 
20ms when > 20

Let's wait for the next move to see if I can close this one

**Comment by sdrobs** [comment]
> Absolutely no one or your speaker wants to hear a dozen Millis on the buy playing at the same time, thus the delay

It might surprise you, but I actually prefer hearing the old way, with all of the sounds at once. Many people have used the old version of aggr for years, and their trading styles depend on small details like the audio not having the delays etc. Audio delays are problematic in my opinion, because the point of this tool is to alert trades in realtime. Any delay or skew from realtime seems to go against the original point of the tool.

**Comment by Tucsky** [comment]
I implemented the delay on v2 as well  ! and I'm glad I did
aggr.trade makes it look like every trade come smoothly, in sequence, but during large move, exchanges events might get chunky  and include a lot a once (but still not quite the same ms right) LOT coming at once which would sound really really bad

@sdrobs is the difference with v2 still that big now with the fix ?

**Comment by sdrobs** [comment]
@Tucsky 

I've been using https://tucsky.github.io/SignificantTrades/ for the last few years, up until about a week ago when it was announced it would stop working. I'm not too familiar with the versioning, was this on v2 or something older? I'm very used to the older setup at least.

I'll check the audio on v3 again soon- when I tried it the other day it was at least multiple seconds delayed at times, and I had to close it because it was throwing me off.

**Comment by Tucsky** [comment]
Original (v0 - v2) had hardcoded sounds but it did sounded really good :))
Am ready to change the default settings for it if we find one that sound more like "the original"

**Comment by sdrobs** [comment]
@Tucsky is there a specific reason you don't just leave up the classic version of 'significant trades' with all the old settings intact like others have asked for? Is it an issue of costing more, or is it something else?

**Comment by Tucsky** [comment]
> @Tucsky is there a specific reason you don't just leave up the classic version of 'significant trades' with all the old settings intact like others have asked for? Is it an issue of costing more, or is it something else?

What setting are you referring to ? there was no audio settings in classic.. just on/off button

**Comment by sdrobs** [comment]
@Tucsky Sorry I don't mean completely classic. I just mean the version at https://tucsky.github.io/SignificantTrades/ that was working a week ago.

**Comment by Tucsky** [comment]
V2 audio have been restored (as default) **It is not optimized**, but it sounds the same now.
The default assignation is temporary, I will put it in a preset once the presets feature is done

the implementation required to change a few things on the way we process audio scripts : 

- before we had a `gain` and `duration` variables based of current volume / **next threshold**, now only a `ratio` variable which refer to the current trade volume / **significant threshold**. 
- added minimum gain as it is the case on v2, which makes trades sounds bigger than they are (v2 way amirite)

Original code from V2 :
```
if (side === "buy") {
  if (variant === 0) {
    this.play(
      659.26 * pitch,
      Math.sqrt(factor) / 10,
      0.1 + Math.sqrt(factor) / 10
    );
  } else if (variant === 1) {
    this.play(
      659.26 * pitch,
      0.05 + Math.sqrt(factor) / 10,
      0.1 + factor * 0.1
    );
    setTimeout(
      () =>
        this.play(
          830.6 * pitch,
          0.05 + Math.sqrt(factor) / 10,
          0.1 + factor * 0.1
        ),
      80
    );
  } else {
    this.play(
      659.26 * pitch,
      0.05 + Math.sqrt(factor) / 25,
      0.1 + factor * 0.1
    );
    setTimeout(
      () =>
        this.play(
          830.6 * pitch,
          0.05 + Math.sqrt(factor) / 25,
          0.1 + factor * 0.1
        ),
      80
    );
    setTimeout(
      () =>
        this.play(
          987.76 * pitch,
          0.05 + Math.sqrt(factor) / 25,
          0.1 + factor * 0.1
        ),
      160
    );
    setTimeout(
      () =>
        this.play(
          1318.52 * pitch,
          0.05 + Math.sqrt(factor) / 10,
          0.1 + factor * 0.1
        ),
      240
    );
  }
} else {
  if (variant === 0) {
    this.play(
      493.88 * pitch,
      Math.sqrt(factor * 1.5) / 10,
      0.1 + Math.sqrt(factor) / 10
    );
  } else if (variant === 1) {
    this.play(
      493.88 * pitch,
      0.05 + Math.sqrt(factor * 1.5) / 10,
      0.1 + factor * 0.1
    );
    setTimeout(
      () =>
        this.play(
          392 * pitch,
          0.05 + Math.sqrt(factor * 1.5) / 10,
          0.1 + factor * 0.1
        ),
      80
    );
  } else {
    this.play(
      493.88 * pitch,
      0.05 + Math.sqrt(factor) / 25,
      0.1 + factor * 0.1
    );
    setTimeout(
      () => this.play(369.99 * pitch, 0.05 + Math.sqrt(factor * 1.5) / 10, 0.2),
      80
    );
    setTimeout(
      () => this.play(293.66 * pitch, 0.05 + Math.sqrt(factor * 1.5) / 10, 0.2),
      160
    );
    setTimeout(
      () =>
        this.play(
          246.94 * pitch,
          0.05 + Math.sqrt(factor * 1.5) / 10,
          0.1 + factor * 0.1
        ),
      240
    );
  }
}
```

Rough translation to V3
```
[
  {
    "id": "threshold",
    "amount": 100000,
    "buyAudio": `play(659.26, Math.sqrt(ratio) / 10, 0.1 + Math.sqrt(ratio) / 10, 0)`,
    "sellAudio": `play(493.88, Math.sqrt(ratio * 1.5) / 10, 0.1 + Math.sqrt(ratio) / 10, 0)`
  },
  {
    "id": "significant",
    "amount": 100000,
    "buyAudio": `play(659.26, 0.05 + Math.sqrt(ratio) / 10, 0.1 + ratio * 0.1, 0);
play(830.6, 0.05 + Math.sqrt(ratio) / 10, 0.1 + ratio * 0.1, 0.08)`,
    "sellAudio": `play(493.88, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.1 + ratio * 0.1, 0);
play(392, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.1 + ratio * 0.1), 0.08)`
  },
  {
    "id": "huge",
    "amount": 1000000,
    "gif": "cash",
    "buyAudio": `play(659.26, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0);
play(830.6, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0.08);
play(987.76, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0.16);
play(1318.52, 0.05 + Math.sqrt(ratio) / 10, 0.1 + ratio * 0.1, 0.24)`,
    "sellAudio": `play(493.88, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0);
play(369.99, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.2, 0.08);
play(293.66, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.2, 0.16);
play(246.94, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.1 + ratio * 0.1, 0.24)`
  },
  {
    "id": "rare",
    "amount": 10000000,
    "gif": "explosion",
    "buyAudio": `play(659.26, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0);
play(830.6, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0.08);
play(987.76, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0.16);
play(1318.52, 0.05 + Math.sqrt(ratio) / 10, 0.1 + ratio * 0.1, 0.24)`,
    "sellAudio": `play(493.88, 0.05 + Math.sqrt(ratio) / 25, 0.1 + ratio * 0.1, 0);
play(369.99, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.2, 0.08);
play(293.66, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.2, 0.16);
play(246.94, 0.05 + Math.sqrt(ratio * 1.5) / 10, 0.1 + ratio * 0.1, 0.24)`
  }
]
```

I'm sure the math in there can be simplified

**Comment by sdrobs** [comment]
@Tucsky Appreciate the work you put in here by the way- is 3PK1bBK8sG3zAjPBPD7g3PL14Ndux3zWEz still a valid address of yours that I can send a btc donation to?

**Comment by Tucsky** [comment]
@sdrobs 
Glad you asked :)) Yes it is still a perfectly valid address of course. Thank you for considering 🙏

About yesterday **hot** fix, I actually deployed the audio with a syntax error in it. I was in such a rush lol Anyway it is fixed now. 

If still no sounds come out from the pane, the syntax error might still be there in your stored settings so in this case -> reset to default is the best option
![image](https://user-images.githubusercontent.com/5738336/122022749-310c2e80-cdc7-11eb-8c31-7a7edf3c3529.png)

**Comment by sdrobs** [comment]
@Tucsky Cool, I sent you some btc as a show of support since I use 'significant trades' regularly. Cheers!

**Comment by sdrobs** [comment]
@Tucsky Just want to double check, did you receive it okay?

**Comment by Tucsky** [comment]
> @Tucsky Just want to double check, did you receive it okay?
Massive thank to you sir ❤
Also please check mail.
