### ISSUE TITLE
Custom Liquidation Sounds (playurl)

### ISSUE THREAD

**Issue by Tucsky** [Tucsky/aggr#51]
### Discussed in https://github.com/Tucsky/aggr/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **fmhc** June 27, 2021</sup>
Hello, I was thinking of custom liquidation sounds with an mp3 - is that possible within the current scripting already or would i need to add a function similar implemented like play(), e.g. playmp3() which adds frontend mp3 play functionality with a link?

![image](https://user-images.githubusercontent.com/3387385/123554893-a3472080-d782-11eb-8fd5-16fc4857d74e.png)
</div>

**Comment by lmvdz** [comment]
I made a playurl work on my repo, I had linked the commit to show but realized my fork wasn't up to date with upstream

**Comment by Tucsky** [comment]
I really need to stop push directly on master lol.. It wasn't ready
But audio refactoring is
