### ISSUE TITLE
Futures pane missing

### ISSUE THREAD

**Issue by ShineDAO** [Tucsky/aggr#55]
Around 2 weeks ago the application had a Futures pane between Spot pane and Rekt pane. 
Now It seems there was some update and there is just Spot and Rekt, however, what happened to Futures?

**Comment by Tucsky** [comment]
removed it

**Comment by ShineDAO** [comment]
@Tucsky thx for the quick reply.

I think I understand now, so you merged the spot and futures into one pane by default now. What was the reason for that? I really liked the split before to be honest. Also thank you for explaining how to do it again, but If you are still developing the product I think it would be great if you have a button which just filters Spot vs. Futures and selects those exchanges that you mentioned. it would benefit the UX tremendously.

**Comment by Tucsky** [comment]
added filters in the search window
you can choose spot, perps of futures, not 100% sure it covers all the pairs and types, but it's an improvement :))

**Comment by Tucsky** [comment]
alright closing this now
