### ISSUE TITLE
Deleting a workspace via the dropdown trashcan icon does not work

### ISSUE THREAD

**Issue by polygxn** [Tucsky/aggr#56]
Title kinda sums it up, you can still remove workspaces with the three dots menu if you have the workspace open you want to remove, but not with the one from the dropdown.

https://i.imgur.com/VEA8buJ.png

**Comment by Tucsky** [comment]
I believe it's fixed already
![image](https://user-images.githubusercontent.com/5738336/125005564-56095f80-e05c-11eb-8dc9-fc46c8cc2ef8.png)
^ no more dropdown for other workspaces

will deploy to public v3 eow
