### ISSUE TITLE
Bybit not appearing

### ISSUE THREAD

**Issue by Gitinghubed** [Tucsky/aggr#57]
Liked  v3 but bybit not appearing 
Thanks

**Comment by Tucsky** [comment]
If you really want bybit you can still add it :

![Screenshot_20210712-185251](https://user-images.githubusercontent.com/5738336/125326708-9f023200-e342-11eb-850f-e9e734f0526b.jpg)
![Screenshot_20210712-185332](https://user-images.githubusercontent.com/5738336/125326727-a32e4f80-e342-11eb-80b7-524ed3a8f759.jpg)
