### ISSUE TITLE
Referencing past data in scripts

### ISSUE THREAD

**Issue by jhabermas** [Tucsky/aggr#60]
Is it possible to reference past data in scripts, similar to how subscript operator works in pine script (e.g. close[2])? Let's say I want to know the value of `$price.close` or `sma` 4 bars ago. Is that possible? If not how would I go about implementing it?
Thanks

**Comment by Tucsky** [comment]
yes of course, you make a variable

```
close = $price.close
plotline(close[4])
plotline(close[8])
```

from there the script knows there is a variable name "close" with value `$price.close` and will keep values in memory for 8 bars
