### ISSUE TITLE
Trade pane text color is very dim

### ISSUE THREAD

**Issue by yerb** [Tucsky/aggr#64]
Seems to be the latest changes that made Trades pane text color dim. I assume it has something to do with `percentToSignificant`
If you can add a separate color picker for text for thresholds?

**Comment by Tucsky** [comment]
what are your thresholds ?

**Comment by yerb** [comment]
10k, 200k, 500k, 2mil

**Comment by yerb** [comment]
looks like this https://imgur.com/a/OIKBnsW

**Comment by Tucsky** [comment]
why would you set minimum at 1k, significant at 200k 🤔 
1k is literally noise then

**Comment by yerb** [comment]
sometimes i set it low to see what the noise is doing :)

now its 10k https://imgur.com/a/OIKBnsW

can you set the lowest threshold value for text transparency?

**Comment by Tucsky** [comment]
1K is 0.5% of 200k, the color just reflect this big volume difference
I add 25% opacity in any case just to make it readable if you focus on it I guess, so 1k out of 200k is 25.5% opacity

there need to be some contrast between a 10k and 200k trade
![image](https://user-images.githubusercontent.com/5738336/126756279-6d0f8d37-89e2-48d0-9441-06c0a4bbdeb1.png)

I can change to 33% minimum even tho I feel like it already affect the overall contrast of the feed
Another solution would be to set darker colors for minimum threshold

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/126757486-b905dd6f-5273-445d-8d94-3381469ed80c.png)
v2 for reference (10k 200k 2M)

**Comment by yerb** [comment]
this is ok, did you set 33%?

Sometimes there are thousands of 1.4k orders which is a big order broken down and its useful for me to see that.

**Comment by yerb** [comment]
Probably too much complication to add custom lowest text transparency for thresholds.

**Comment by yerb** [comment]
this is ok, did you set 33%?

Sometimes there are thousands of 1.4k orders which is a big order broken down and its useful for me to see that.

**Comment by yerb** [comment]
What makes text turn black?
![chrome_2021-07-23_10-57-38](https://user-images.githubusercontent.com/1695487/126759892-52a6457d-d82b-492f-971e-3ec2a86abadf.png)

**Comment by Tucsky** [comment]
bright background will flip text color to black
