### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by adaamz** [Tucsky/aggr#65]
Hi,
is there any recommendation on what settings should lower cpu usage? I have 5s chart refresh time, show only liquidations tab and the v3 application page takes 10-20% cpu, that is insane for almost static page :)

**Comment by Tucsky** [comment]
Hi @adaamz 
I'm sorry this app is too demanding for your CPU power.

For trade feed you can try lowering rendered trade count (but default is already low) or disabling animations.
Chart is a very high cpu consumer as well but if you say you already have it set to 1 update every 5s this is already extremely low. Not much you can do, sorry

**Comment by Tucsky** [comment]
Aggr not static at all, quite the opposite actually
Unlike most platforms (tv, tradinglite, exo etc) that use their own centralized server to dispatch aggregated / compressed market data, aggr connect directly to the exchanges api processing thousand RAW trades per sec. 
Default settings lead to 14 concurrent websocket connections each handling multiple channel subscriptions.
On average if you let it run for 1 day it will process about 10M trades.

I put A LOT of time and attention to performance, even tho I tend to agree you need a decent computer to run this thing smoothly. All the processing there is done for a reason, at this stage I'm afraid there is not much room for improvement  (in the code itself that is)

**Comment by Tucsky** [comment]
https://webmshare.com/Pbe40

Here I let it run for on default settings, see the CPU usage I get

- First when running only feeds, relatively small window
about 0 to 20% , rarely goes above 10 unless volume spike or you interact with it
- at 1:44 I disable animations, you can see small improvement
- then I add chart (about 4:00 in)
- then I put it full screen (5:40)
but there was no spike in volume, cpu remained low

**Comment by Tucsky** [comment]
Also, setting more reasonable thresholds and longer aggregation might help since more trades will get "merged"
![image](https://user-images.githubusercontent.com/5738336/127171436-57982cba-2af0-4651-8e4d-6cca4a65a972.png)
![image](https://user-images.githubusercontent.com/5738336/127171286-acce5366-2177-4dbe-a052-3c9fcd0937f5.png)
default threshold are too degen imo

**Comment by adaamz** [comment]
Thanks for your replies, really appreciate it.
Without chart and aggregation changed to 1000ms (never thought it's editable) it takes 5-10% cpu, which is better 👍🏻.
In this case when you don't have any own backend then it is sure thing that client must do the calculations on itself and cpu consumption is much higher than static page, seems logic to me.
I will close this issue as you provided some hints which can decrease cpu usage, thx again.
