### ISSUE TITLE
command not found while building My own aggr client docker

### ISSUE THREAD

**Issue by Ken-n** [Tucsky/aggr#67]
Hi Tucky, I'm a beginner of Linux Command LIne. I encountered a this issue while trying to build my own aggr client docker on my Macbook via the Terminal.

The error was showed below:
===========================
Kens-MacBook-Pro:~ ken$ cd aggr
Kens-MacBook-Pro:aggr ken$ docker build -t aggr-chart .
-bash: docker: command not found
============================

Looking forward your help.
Best,
Ken

**Comment by lmvdz** [comment]
Did you install docker?

**Comment by Ken-n** [comment]
> Did you install docker?
Ah😓, thank you Imavdz, I had installed docker desktop later then, but a new issue occurred. 
==================
**Kens-MacBook-Pro:aggr ken$ docker build -t aggr-chart
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile**
======================
With reading the instruction "you need to set the API_URL as environment variable for your own installation, if you want to use that.", does the pre-setting matter?

Thank you again!

**Comment by Tucsky** [comment]
I believe you have to pass the path of the project folder, if you are already in you just use "." to reference current folder. 

`docker build -t aggr-chart .` <- notice the dot at the end, that's the missing argument!

`-t xxx` is just the name of the builded docker image, you can use whatever

Once it's done you will see this image in the docker app

![image](https://user-images.githubusercontent.com/5738336/132217375-1b6ae9f2-09fe-470a-8c7d-9d06239d6c29.png)

Just clic run button at the end of the line, then you can specify a port in which the app will be accessible in the browser
![image](https://user-images.githubusercontent.com/5738336/132217536-26e75a6d-d060-4a02-a4a0-af60c682fe85.png)

Clic run again in the popup
![image](https://user-images.githubusercontent.com/5738336/132217638-3f18da15-fef6-4601-82be-a56ea7d518c0.png)

And that's it, navigate to http://localhost:8090/ and you should see the app.

Heres whats the logs should look like on the docker
![image](https://user-images.githubusercontent.com/5738336/132217683-27e1aef0-e66a-4fb5-8c8b-c7e8c2d300dd.png)
It's just nginx webserver starting...

**Comment by Ken-n** [comment]
> I believe you have to pass the path of the project folder, if you are already in you just use "." to reference current folder.
> 
> `docker build -t aggr-chart .` <- notice the dot at the end, that's the missing argument!
> 
> `-t xxx` is just the name of the builded docker image, you can use whatever
> 
> Once it's done you will see this image in the docker app
> 
> ![image](https://user-images.githubusercontent.com/5738336/132217375-1b6ae9f2-09fe-470a-8c7d-9d06239d6c29.png)
> 
> Just clic run button at the end of the line, then you can specify a port in which the app will be accessible in the browser
> ![image](https://user-images.githubusercontent.com/5738336/132217536-26e75a6d-d060-4a02-a4a0-af60c682fe85.png)
> 
> Clic run again in the popup
> ![image](https://user-images.githubusercontent.com/5738336/132217638-3f18da15-fef6-4601-82be-a56ea7d518c0.png)
> 
> And that's it, navigate to http://localhost:8090/ and you should see the app.
> 
> Heres whats the logs should look like on the docker
> ![image](https://user-images.githubusercontent.com/5738336/132217683-27e1aef0-e66a-4fb5-8c8b-c7e8c2d300dd.png)
> It's just nginx webserver starting...

Dear Owner, 
Thanks for your reply and specific explanation.

I succeeded to run the image, but have dumb question:
What's then? I didn't see any price chart later on. 
Should I do something further more? but I didn't understand the Configuration part in the instruction page.
![image](https://user-images.githubusercontent.com/32905254/132605278-78707515-bbdc-46bc-9ac4-0782f34a4b3a.png)

**Comment by Tucsky** [comment]
lol yeah I was wondering too, what are you trying to achieve there ? :)

I see some perks in building your own aggr instance like monitor markets that I don't provide any data for or develop additional functionalities on top of the core, but if you don't know what you are doing might as well use the production domains 🤷🏼‍♂️ 
- https://v3.aggr.trade/
- https://aggr.trade/
- http://tucsky.github.io/aggr (alt)

the historical chart data on the production domains is provided by https://api.aggr.trade/ **which is only intended to serve the data to the domains I listed above** so it makes sense that the chart appear empty on your builded app

For persisting chart data over time, you need to collect it from the exchanges and store it somewhere,
https://github.com/Tucsky/aggr-server will do that

then connect the client with your server part using API_URL in the .env of the client

**Comment by Ken-n** [comment]
> lol yeah I was wondering too, what are you trying to achieve there ? :)

Hi Tucsky, actually,  what I was seeking for is a gadget/widget of changing prices that can display Always-on-Top of my screen//browser. So that I won't miss dumps or pumps while browsing something else on the computer, just like the right-top on the screenshot blew that I take from a Whalepool's live streaming.
![image](https://user-images.githubusercontent.com/32905254/132697811-d6c2566d-df1a-43a7-8a18-0db09b9d11b9.png)
Someone there given a link of your repo, that's how I encounter your repo and kicked off with trying those seemingly simple command lines.😂

**Comment by Tucsky** [comment]
So sorry I missed your message 😣 

>Actually, what I was seeking for is a gadget/widget of changing prices that can display Always-on-Top of my screen//browser

1. solution 1
I wouldn't look into build / dev anything for that, just open [aggr.trade](https://aggr.trade), disable chart in settings, make it a small window and thats pretty much it I guess

I would recommand to use https://chrome.google.com/webstore/detail/popup-window/nnlippelgfbglbhiccffmnmlnhmbjjpe along that solution

2. solution 2
go to v3.aggr.trade hit the ⬇️ icon
![image](https://user-images.githubusercontent.com/5738336/135933014-24948206-1ef3-46b3-9fce-d206ba48c487.png)
to install the app on desktop, open it, remove chart pane, extend trade feed to take all available space and voila :)

**Comment by Ken-n** [comment]
Thanks for your following up.:)

> 1. solution 1
>    I wouldn't look into build / dev anything for that, just open [aggr.trade](https://aggr.trade), disable chart in settings, make it a small window and thats pretty much it I guess
Opps, I failed to find the "disable" setting  when I click on the ⚙️ icon on the top-right of my browser.
![image](https://user-images.githubusercontent.com/32905254/135940836-5a1e35ad-2f9e-48a6-aff3-6547925cfe62.png)

>2. solution 2
>    go to v3.aggr.trade hit the ⬇️ icon
>    ![image](https://user-images.githubusercontent.com/5738336/135933014-24948206-1ef3-46b3-9fce-d206ba48c487.png)
Neither could I find the ⬇️ icon when I open https://v3.aggr.trade/ on my browser.
