### ISSUE TITLE
Turn audio on/off for each pane (v3 feature request)

### ISSUE THREAD

**Issue by jaredthirsk** [Tucsky/aggr#7]
What I like to do with v2 but I don't see how to do it in v3:

 - [x] put BTC on a low pitch audio
 - [x] potentially have multiple altcoin panes, so I can keep history
 - [x] put the altcoin I'm trading on a high pitch audio
 - [x] switch to trading to another altcoin: turn the sound for the first altcoin off and the sound for the other altcoin on
 - [x] (sometimes I put ETH on a middle pitch)

(btw, aggr.trade is awesome!)

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/124027410-22429000-d9f3-11eb-94f4-ea97e0753f5a.png)


Alright closing this now
