### ISSUE TITLE
[Suggestion] More time frames

### ISSUE THREAD

**Issue by yerb** [Tucsky/aggr#88]
If its not too much work or server load, I would like to see more time frames:
8h
12h
2d
3d
1w

**Comment by Tucsky** [comment]
![image](https://user-images.githubusercontent.com/5738336/131729223-855f1336-5647-4d9b-a619-d734f06b6db0.png)
There is not much room, as you can see, I restarted the whole server yday (ram went from 100% to 40%) but it's going back to 100% RAM usage by friday looks like ..
InfluxDB is using all that, not the backend app (divided in two apps, eth+btc using 250mb ram, alts 300mb)
influx uses multiple gigs, I got 12 total

working on optimization on [back end](https://github.com/Tucsky/aggr-server) rn
if I notice improvement I will for sure
and bring back 21m as well

**Comment by yerb** [comment]
would it help to have server side calculation up to 1m and the rest client side?
