### ISSUE TITLE
Choose btcusd instead of picking all markets manually in v3

### ISSUE THREAD

**Issue by davydof** [Tucsky/aggr#9]
In v2 there is an easy way how to choose all markets with btcusdt/btcusdt, e.g.:
```https://btcusd.aggr.trade```

In v3 I should pick all markets manually which is pretty ugly

Will v3 support to choose all markets by btcusd/ethusd/ethbtc etc.?

**Comment by Tucsky** [comment]
Would be easier if exchanges could agree on using the same symbol ids :) 
This automatic pair matching was nice for the beginners for sure, only down side of that is no one knew anything about the actual pair being watched behind the user input "btcusd" Is it spot ? perp ? 
> In v3 I should pick all markets manually which is pretty ugly

Actually a feature ;)

But we do need to work on a way to make it easier for anyone to quicky jump on a pair
for exemple with this query in the search box you cover most of it  (here using link as base)
![image](https://user-images.githubusercontent.com/5738336/121821746-43894980-cc9b-11eb-8011-d87f7bd29840.png)
 tho after making this quick try I notice that poloniex doesn't follow shit about the naming conventions 😄 

We could add "add all" button, would 100% crash if too many results but that a solution

`link\W*(usdt?|perp|swap)?(-SWAP)?$`

I can add some parameter in the url https://aggr.trade/linkusd that would trigger this custom matching
that would create a new workspace for that pair (or use workspace with id linkusd)
and auto add the markets above (if a new workspace)

but we need to be able to select those separately, that will stay

**Comment by davydof** [comment]
@Tucsky 
> I can add some parameter in the url https://aggr.trade/linkusd that would trigger this custom matching
that would create a new workspace for that pair (or use workspace with id linkusd)
and auto add the markets above (if a new workspace)
but we need to be able to select those separately, that will stay

does it work?)

**Comment by Tucsky** [comment]
@davydof no

I was suggesting this as an alternative
issue was about not selecting all markets manually at that time, but I added group selection feature since so this issue is done

Now about creating workspace targeting specific markets from url, will see what I can do
