### ISSUE TITLE
Sounds not working on Safari browsers

### ISSUE THREAD

**Issue by GabrielBuragev** [Tucsky/aggr#92]
Tested the demo (https://v3.aggr.trade/) on Safari browser version 14.1 and it seems like the sounds dont work at all. 
Do you have any idea why this happens? 

Awesome project by the way!

**Comment by Tucsky** [comment]
Thank you sir for the report however sound is working perfectly for me, even on Safari
Please export workspace here so I can take a look at your settings (settings > workspaces > blue button > download)
<img src="https://user-images.githubusercontent.com/5738336/132834487-8c02721f-ae3b-49ab-beb8-d8e44f847771.png" width="400" >


Also 
- make sure audio is enabled and volume is not 0
- check that a you have a trades feed on, that's where the sounds supposed to come from, if no trade feed on -> no sounds
- check that the pane volume is not 0 or muted, you can check audio threshold too
<img src="https://user-images.githubusercontent.com/5738336/132834913-e714296a-2938-460e-8239-21d62ca9677b.png" width="400" >

**Comment by GabrielBuragev** [comment]
True, just enabled the sound from the settings menu and everything works fine on Safari. 
I thought it is set to "On" from the beggining.
Thanks for the help, you can close this issue!
