### ISSUE TITLE
Is it possible to have separate scale with measurement units in for volumes/liqs/etc?

### ISSUE THREAD

**Issue by deandreee** [Tucsky/aggr#94]
I know about "position in chart" option, but that only gives me new scale. I want to see the units/values on x axis, otherwise it's difficult to analyze - I have to mouseover and then check the top left corner for values.

Adding new pane kinda gives me this - new scale with values on X axis, but there's another problem - panes don't automatically sync Y axis, I need to zoom each one manually.

Adding image with example of what I'm trying to achieve. Any advice would be greatly appreciated. Thanks!

![b416e8c5-8b53-46ac-854d-ded6ea9acfe4](https://user-images.githubusercontent.com/48177900/134145796-962e4443-f928-4fce-b2ed-7b9e4177b851.png)

**Comment by Tucsky** [comment]
Right now the underlying charting tool does not support any more than 1 price axis (left or right). So this is simply not possible atm

> otherwise it's difficult to analyze
This I don't get it tbh, what's the benefits of knowing the exact amount in each bars? I just watch the chart and how it look relatively to past data, but maybe that's just me. I do not care if there is 10M 100M 1B in volume I just watch delta (not total B/S volume as you have it in your chart), and how big the liquidation bar are relatively to previous swings. 
I don't even use the legend. No legend = better performance 😄

**Comment by Tucsky** [comment]
On another note someone forked the lib in order to add that, so there is hope
My concern also is how bad the performance will be with multiple panes on the chart. Multiply the drawing time by n panes (for grid, axis, price tag and crosshair)

**Comment by deandreee** [comment]
Thanks for the quick answer! 

> what's the benefits of knowing the exact amount in each bars

1. Personal visual preference
2. Might actually want to long when liqs > specific amount instead of relative
3. Relative might sometimes paint a false picture, e.g. it's a slow day and current liq/vol looks big compared to what's currently loaded on the chart (few hours), but it's actually small compared to volumes over last week/month etc.

Just an example of how I'd use them. I find these use cases important, but I also have a very specific taste on what I want to see in the charts.

Closing this issue since the question is answered and feature is not possible.
